#!/usr/bin/env bash
# Sync Codex config from dotfiles SSOT to Codex-native dotfiles targets.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json          (MCP servers)
#   - $DOT_DIR/AGENTS.md                 (shared global instructions)
#   - $DOT_DIR/.agents/skills/*          (shared skill definitions)
#   - $DOT_DIR/.claude/format.md         (referenced instructions)
#   - $DOT_DIR/.claude/pir-handoff.md    (referenced instructions)
#   - $DOT_DIR/.claude/user-feedback-protocol.md (referenced instructions)
#   - $DOT_DIR/.claude/agent-delegation.md     (referenced instructions)
#   - $DOT_DIR/.claude/pir2-protocol.md        (referenced instructions)
#   - $DOT_DIR/.claude/dev-server.md           (referenced instructions)
#   - $DOT_DIR/.claude/subagent-permissions.md (referenced instructions)
#   - $DOT_DIR/.claude/agents/*.md       (legacy mirror input only; disabled by default)
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.codex/config.toml
#   - $DOT_DIR/.codex/AGENTS.md
#   - $DOT_DIR/.codex/format.md
#   - $DOT_DIR/.codex/pir-handoff.md
#   - $DOT_DIR/.codex/user-feedback-protocol.md
#   - $DOT_DIR/.codex/agent-delegation.md
#   - $DOT_DIR/.codex/pir2-protocol.md
#   - $DOT_DIR/.codex/dev-server.md
#   - $DOT_DIR/.codex/subagent-permissions.md
#   - $DOT_DIR/.codex/agents/<name>.toml     (legacy mirror only when SYNC_CODEX_LEGACY_MIRROR=1)
#   - $DOT_DIR/.codex/skills/<name>/         (legacy mirror only when SYNC_CODEX_LEGACY_MIRROR=1)
#
# Re-running is idempotent.
#
# Native overlay policy:
#   Strict mirroring of .claude/agents and .agents/skills into .codex is disabled
#   by default. .agents/skills is the shared core, while .codex/agents and
#   .codex/skills are Codex-native overlays. Set SYNC_CODEX_LEGACY_MIRROR=1 only
#   when intentionally regenerating the old mirror snapshots.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"
CLAUDE_DIR="${DOT_DIR}/.claude"
CODEX_DIR="${DOT_DIR}/.codex"
CODEX_BASE_CONFIG="${CODEX_DIR}/config.base.toml"
CODEX_CONFIG="${CODEX_DIR}/config.toml"
CODEX_AGENTS_DIR="${CODEX_DIR}/agents"
CODEX_SKILLS_DIR="${CODEX_DIR}/skills"
SHARED_SKILLS_DIR="${DOT_DIR}/.agents/skills"

log()  { echo "[sync-codex] $*"; }
warn() { echo "[sync-codex] warn: $*" >&2; }

if ! command -v jq >/dev/null 2>&1; then
  warn "jq not found, skipping sync"
  exit 0
fi

# Windows-native jq emits CRLF line terminators, which leak \r into generated
# TOML keys/values (e.g. [mcp_servers."codex\r"]) and break key matching.
# Wrap jq to strip CR from its output so generation is byte-clean on any OS.
# Defined AFTER the availability check above so `command -v jq` still tests the
# real binary, not this function.
jq() { command jq "$@" | tr -d '\r'; }

if [ ! -f "$MCP_SRC" ]; then warn "missing $MCP_SRC"; exit 0; fi
if [ ! -f "$AGENTS_SRC" ]; then warn "missing $AGENTS_SRC"; exit 0; fi
if [ ! -f "$CODEX_BASE_CONFIG" ]; then warn "missing $CODEX_BASE_CONFIG"; exit 0; fi

mkdir -p "$CODEX_DIR" "$CODEX_AGENTS_DIR" "$CODEX_SKILLS_DIR"

toml_quote() {
  jq -Rn --arg s "$1" '$s'
}

toml_array() {
  jq -c '.' | sed 's/,/, /g'
}

build_hooks_section_toml() {
  echo
  echo "# ---- AUTO-GENERATED hooks (dotfiles SSOT) ----"
  echo "[features]"
  # Codex 公式の現行フラグは `hooks = true`（`codex_hooks` は deprecated alias）
  echo "hooks = true"
  echo
  echo "[[hooks.PostToolUse]]"
  echo 'matcher = "Edit|Write|MultiEdit"'
  echo
  echo "[[hooks.PostToolUse.hooks]]"
  echo 'type = "command"'
  printf 'command = %s\n' "$(toml_quote "bash ${DOT_DIR}/etc/sync-codex.sh")"
}

# プロジェクト trust ([projects."<abs path>"]) はマシン固有の絶対パスのため共有 SSOT
# (config.base.toml) には置かない。各マシンの config.toml にだけ存在し、再生成で消えると
# Codex が毎回 trust を聞いてくるので、既存 config.toml の [projects.*] 節をそのまま引き継ぐ。
preserve_projects_toml() {
  [ -f "$CODEX_CONFIG" ] || return 0
  local projects
  projects="$(awk '
    /^\[projects\./ { cap=1; print; next }
    /^\[/           { cap=0 }
    cap             { print }
  ' "$CODEX_CONFIG")"
  # 末尾の空行を除去
  projects="$(printf '%s' "$projects" | sed -e :a -e '/^\n*$/{$d;N;ba}')"
  [ -n "$projects" ] || return 0
  echo "# ---- preserved per-machine project trust (machine-local; not in SSOT) ----"
  printf '%s\n' "$projects"
  echo
}

write_codex_config() {
  # Guard: 既存 config.toml が AUTO-GENERATED ヘッダを持たない場合は手書きと見なし保護する
  if [ -f "$CODEX_CONFIG" ] && ! head -1 "$CODEX_CONFIG" | grep -q '^# AUTO-GENERATED by dotfiles/etc/sync-codex.sh'; then
    warn "refusing to overwrite hand-edited $CODEX_CONFIG (no AUTO-GENERATED header)"
    warn "remove the file or restore the header to enable sync"
    return 0
  fi

  local tmp toml_err
  tmp="$(mktemp "${CODEX_DIR}/config.toml.tmp.XXXXXX")"

  {
    echo "# AUTO-GENERATED by dotfiles/etc/sync-codex.sh from SSOT."
    echo "# Edit .codex/config.base.toml or the shared AI workflow SSOT files instead."

    echo
    cat "$CODEX_BASE_CONFIG"
    echo
    preserve_projects_toml
    echo "# ---- AUTO-GENERATED MCP servers from mcp-servers.json ----"

    jq -r '.mcpServers | keys[]' "$MCP_SRC" | while IFS= read -r name; do
      local server type table_name command args env_json env_rendered url
      server="$(jq -c --arg name "$name" '.mcpServers[$name]' "$MCP_SRC")"

      if [ "$(printf '%s' "$server" | jq -r '.codexOnly // false')" = "false" ] &&
         { [ "$(printf '%s' "$server" | jq -r '.claudeCodeOnly // false')" = "true" ] ||
           [ "$(printf '%s' "$server" | jq -r '.openCodeOnly // false')" = "true" ]; }; then
        continue
      fi

      table_name="$(toml_quote "$name")"
      type="$(printf '%s' "$server" | jq -r '.type // (if .url then "remote" else "local" end)')"

      echo
      printf '[mcp_servers.%s]\n' "$table_name"
      echo "enabled = true"

      if [ "$type" = "remote" ]; then
        url="$(printf '%s' "$server" | jq -r '.url // empty')"
        if [ -z "$url" ]; then
          warn "remote MCP server '$name' has no url, skipping"
          continue
        fi
        printf 'url = %s\n' "$(toml_quote "$url")"
        if printf '%s' "$server" | jq -e '.bearer_token_env_var? // empty' >/dev/null; then
          printf 'bearer_token_env_var = %s\n' "$(toml_quote "$(printf '%s' "$server" | jq -r '.bearer_token_env_var')")"
        fi
      else
        command="$(printf '%s' "$server" | jq -r '.command // empty')"
        if [ -z "$command" ]; then
          warn "local MCP server '$name' has no command, skipping"
          continue
        fi
        args="$(printf '%s' "$server" | jq '.args // []' | toml_array)"
        printf 'command = %s\n' "$(toml_quote "$command")"
        printf 'args = %s\n' "$args"

        env_json="$(printf '%s' "$server" | jq -c '.env // {}')"
        if [ "$(printf '%s' "$env_json" | jq 'length')" != "0" ]; then
          # Note: rendered into an intermediate variable to avoid bash 3.2's
          # brace-expansion bug, where literal '{ ... , ... }' inside a single-
          # quoted filter nested in "$(...)" gets mis-expanded into two words.
          env_rendered="$(printf '%s' "$env_json" | jq -r 'to_entries | map("\(.key) = \(.value | @json)") | "{ " + join(", ") + " }"')"
          printf 'env = %s\n' "$env_rendered"
        fi
      fi
    done

    build_hooks_section_toml
  } > "$tmp"

  # TOML 構文検証（python3 が利用可能な場合のみ）
  if command -v python3 >/dev/null 2>&1; then
    if ! toml_err="$(python3 -c 'import sys, tomllib; tomllib.load(open(sys.argv[1], "rb"))' "$tmp" 2>&1)"; then
      warn "generated TOML is invalid, aborting (tmp: $tmp)"
      warn "python3 error: $toml_err"
      return 1
    fi
  else
    warn "python3 not found, skipping TOML syntax validation"
  fi

  mv -f "$tmp" "$CODEX_CONFIG"
  log "wrote $CODEX_CONFIG"
}

copy_with_header() {
  local src="$1" dst="$2" label="$3"
  [ -f "$src" ] || return 0
  {
    printf '<!-- AUTO-GENERATED by etc/sync-codex.sh from %s. Do not edit. -->\n\n' "$label"
    cat "$src"
  } > "$dst"
  log "wrote $dst"
}

copy_codexized_with_header() {
  local src="$1" dst="$2" label="$3"
  [ -f "$src" ] || return 0
  {
    printf '<!-- AUTO-GENERATED by etc/sync-codex.sh from %s. Do not edit. -->\n\n' "$label"
    codexize_stream < "$src"
  } > "$dst"
  log "wrote $dst"
}

codexize_stream() {
  sed \
    -e 's/Claude Code/Codex/g' \
    -e 's/メイン Claude/メイン Codex/g' \
    -e 's/Claude 自身/Codex 自身/g' \
    -e 's/Claude 側/Codex 側/g' \
    -e 's/Claude の/Codex の/g' \
    -e 's/Claude は/Codex は/g' \
    -e 's/Claude が/Codex が/g' \
    -e 's#~/.claude/CLAUDE\.md#~/.codex/AGENTS.md#g' \
    -e 's#~/.claude/agents#~/.codex/agents#g' \
    -e 's#~/.claude/skills#~/.agents/skills#g' \
    -e 's#~/.claude/projects#~/.codex/memories#g' \
    -e "s#\${HOME}/\\.claude#\${HOME}/.codex#g" \
    -e 's#~/.claude/#~/.codex/#g' \
    -e 's#\.claude/CLAUDE\.md#.codex/AGENTS.md#g' \
    -e 's#\.claude/agents#.codex/agents#g' \
    -e 's#\.claude/skills#.agents/skills#g' \
    -e 's#\.claude/settings\.local\.json#.codex/config.toml#g' \
    -e 's#\.claude/settings\.json#.codex/config.toml#g' \
    -e 's#\.claude/#.codex/#g' \
    -e 's/Agent ツール/Codex subagent/g' \
    -e 's/Skill ツール/Codex skill invocation/g' \
    -e 's/TeamCreate/Codex subagent workflows/g' \
    -e 's/サブエージェント/subagent/g' \
    -e 's/claude-sonnet-4-6/gpt-5.5/g' \
    -e 's/haiku/gpt-5.4-mini/g' \
    -e 's/sonnet/gpt-5.5/g' \
    -e 's/opus/gpt-5.5/g'
}

codexize_file_in_place() {
  local file="$1" tmp
  [ -f "$file" ] || return 0
  tmp="$(mktemp "${file}.tmp.XXXXXX")"
  codexize_stream < "$file" > "$tmp"
  mv -f "$tmp" "$file"
}

build_codex_agents_md() {
  local src="$AGENTS_SRC"
  local dst="${CODEX_DIR}/AGENTS.md"
  [ -f "$src" ] || return 0

  {
    cat <<'HEADER'
<!-- AUTO-GENERATED by etc/sync-codex.sh from AGENTS.md.
     Do not edit by hand. Re-run: bash etc/sync-codex.sh
     Codex reads AGENTS.md. This file is generated in Codex-native format. -->

HEADER
    cat "$src"
  } > "$dst"

  log "wrote $dst"
}

quote_yaml_scalar() {
  local raw="$1"
  local decoded="$raw"

  case "$raw" in
    \"*\")
      decoded="$(printf '%s' "$raw" | jq -r . 2>/dev/null || printf '%s' "$raw")"
      ;;
  esac

  printf '%s' "$decoded" | jq -Rs .
}

normalize_codex_skill_frontmatter() {
  local file="$1"
  [ -f "$file" ] || return 0

  local tmp
  tmp="$(mktemp "${file}.tmp.XXXXXX")"

  local fence_count=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "---" ]; then
      fence_count=$((fence_count + 1))
      printf '%s\n' "$line" >> "$tmp"
      continue
    fi

    if [ "$fence_count" -eq 1 ] && [[ "$line" =~ ^([A-Za-z0-9_-]+):[[:space:]]*(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      printf '%s: %s\n' "$key" "$(quote_yaml_scalar "$value")" >> "$tmp"
    else
      printf '%s\n' "$line" >> "$tmp"
    fi
  done < "$file"

  mv -f "$tmp" "$file"
}

extract_agent_frontmatter_value() {
  local file="$1" key="$2" raw
  raw="$(awk -v key="$key" '
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { exit }
    in_frontmatter && index($0, key ":") == 1 {
      sub("^[^:]+:[[:space:]]*", "")
      print
      exit
    }
  ' "$file")"

  case "$raw" in
    \"*|\'*)
      printf '%s' "$raw" | jq -r . 2>/dev/null || printf '%s' "$raw"
      ;;
    *)
      printf '%s' "$raw"
      ;;
  esac
}

extract_agent_body() {
  local file="$1"
  awk '
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { in_frontmatter = 0; body = 1; next }
    body || !in_frontmatter { print }
  ' "$file"
}

codex_agent_model() {
  case "$1" in
    explorer)
      printf '%s' "gpt-5.4-mini"
      ;;
    *)
      printf '%s' "gpt-5.5"
      ;;
  esac
}

codex_agent_reasoning_effort() {
  case "$1" in
    explorer)
      printf '%s' "low"
      ;;
    implementer|refactor-advisor|sentinel-iac|tester)
      printf '%s' "medium"
      ;;
    *)
      printf '%s' "high"
      ;;
  esac
}

convert_agent_to_toml() {
  local src="$1" dst="$2" name description body model reasoning_effort
  name="$(extract_agent_frontmatter_value "$src" "name")"
  description="$(extract_agent_frontmatter_value "$src" "description")"
  if [ -z "$name" ]; then
    name="$(basename "$src" .md)"
  fi
  if [ -z "$description" ]; then
    description="Codex custom agent generated from $(basename "$src")."
  fi
  description="$(printf '%s' "$description" | codexize_stream)"
  body="$(extract_agent_body "$src" | codexize_stream)"
  model="$(codex_agent_model "$name")"
  reasoning_effort="$(codex_agent_reasoning_effort "$name")"

  {
    echo "# AUTO-GENERATED by etc/sync-codex.sh from .claude/agents/$(basename "$src"). Do not edit."
    printf 'name = %s\n' "$(toml_quote "$name")"
    printf 'description = %s\n' "$(toml_quote "$description")"
    printf 'model = %s\n' "$(toml_quote "$model")"
    printf 'model_reasoning_effort = %s\n' "$(toml_quote "$reasoning_effort")"
    printf 'developer_instructions = %s\n' "$(printf '%s' "$body" | jq -Rs .)"
  } > "$dst"

  log "wrote $dst"
}

sync_agents() {
  local src_dir="${CLAUDE_DIR}/agents"
  [ -d "$src_dir" ] || return 0

  for f in "$src_dir"/*.md; do
    [ -f "$f" ] || continue
    convert_agent_to_toml "$f" "${CODEX_AGENTS_DIR}/$(basename "$f" .md).toml"
  done

  for f in "$CODEX_AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    if ! head -1 "$f" | grep -q '^<!-- AUTO-GENERATED by etc/sync-codex.sh'; then
      continue
    fi
    rm -f "$f"
    log "removed legacy generated agent: $(basename "$f")"
  done

  for f in "$CODEX_AGENTS_DIR"/*.toml; do
    [ -f "$f" ] || continue
    if ! head -1 "$f" | grep -q '^# AUTO-GENERATED by etc/sync-codex.sh'; then
      continue
    fi
    if [ ! -f "${src_dir}/$(basename "$f" .toml).md" ]; then
      rm -f "$f"
      log "removed orphan agent: $(basename "$f")"
    fi
  done
}

codexize_markdown_tree() {
  local dir="$1"
  find "$dir" -type f -name '*.md' | while IFS= read -r file; do
    codexize_file_in_place "$file"
  done
}

mirror_skill_to_dir() {
  local src="$1" root="$2" marker_name="$3" label="$4"
  local name dst marker
  name="$(basename "$src")"
  dst="${root}/${name}"
  marker="${dst}/${marker_name}"

  if [ -e "$dst" ] && [ ! -f "$marker" ] &&
     [ ! -f "$dst/.codex-generated-from-claude" ] &&
     [ ! -f "$dst/.generated-from-claude" ]; then
    if diff -qr "$src" "$dst" >/dev/null 2>&1; then
      log "adopting existing mirrored skill as generated: $dst"
    else
      warn "not overwriting non-generated skill: $dst"
      return 0
    fi
  fi

  rm -rf "$dst"
  mkdir -p "$dst"
  cp -a "$src"/. "$dst"/
  rm -rf "$dst/.git"
  normalize_codex_skill_frontmatter "$dst/SKILL.md"
  codexize_markdown_tree "$dst"
  touch "$marker"
  log "${label} skill: $name"
}

cleanup_generated_skill_orphans() {
  local root="$1" marker_name="$2" src_dir="$3" label="$4"
  local d
  for d in "$root"/*; do
    [ -d "$d" ] || continue
    [ -f "$d/$marker_name" ] || continue
    if [ ! -d "${src_dir}/$(basename "$d")" ]; then
      rm -rf "$d"
      log "removed orphan ${label} skill: $(basename "$d")"
    fi
  done
}

sync_skills() {
  local src_dir="$SHARED_SKILLS_DIR"
  [ -d "$src_dir" ] || return 0

  for d in "$src_dir"/*; do
    [ -d "$d" ] || continue
    mirror_skill_to_dir "$d" "$CODEX_SKILLS_DIR" ".codex-generated-from-shared" "Codex mirror"
  done

  cleanup_generated_skill_orphans "$CODEX_SKILLS_DIR" ".codex-generated-from-shared" "$src_dir" "Codex mirror"
  cleanup_generated_skill_orphans "$CODEX_SKILLS_DIR" ".codex-generated-from-claude" "$src_dir" "legacy Codex mirror"
  cleanup_generated_skill_orphans "$CODEX_SKILLS_DIR" ".generated-from-claude" "$src_dir" "legacy Codex mirror"
}

sync_legacy_mirrors_if_requested() {
  if [ "${SYNC_CODEX_LEGACY_MIRROR:-0}" != "1" ]; then
    log "skipped .codex/agents strict mirror (native overlay; set SYNC_CODEX_LEGACY_MIRROR=1 for legacy regeneration)"
    log "skipped .codex/skills strict mirror (shared core lives in .agents/skills; .codex/skills is native overlay)"
    return 0
  fi

  warn "SYNC_CODEX_LEGACY_MIRROR=1 is enabled; attempting legacy .codex/agents and .codex/skills mirror generation"
  sync_agents
  sync_skills
}

write_codex_config
build_codex_agents_md
copy_codexized_with_header "${CLAUDE_DIR}/format.md" "${CODEX_DIR}/format.md" ".claude/format.md"
copy_codexized_with_header "${CLAUDE_DIR}/pir-handoff.md" "${CODEX_DIR}/pir-handoff.md" ".claude/pir-handoff.md"
copy_codexized_with_header "${CLAUDE_DIR}/user-feedback-protocol.md" "${CODEX_DIR}/user-feedback-protocol.md" ".claude/user-feedback-protocol.md"
copy_codexized_with_header "${CLAUDE_DIR}/agent-delegation.md" "${CODEX_DIR}/agent-delegation.md" ".claude/agent-delegation.md"
copy_codexized_with_header "${CLAUDE_DIR}/pir2-protocol.md" "${CODEX_DIR}/pir2-protocol.md" ".claude/pir2-protocol.md"
copy_codexized_with_header "${CLAUDE_DIR}/dev-server.md" "${CODEX_DIR}/dev-server.md" ".claude/dev-server.md"
copy_codexized_with_header "${CLAUDE_DIR}/subagent-permissions.md" "${CODEX_DIR}/subagent-permissions.md" ".claude/subagent-permissions.md"
sync_legacy_mirrors_if_requested

log "done"
