#!/usr/bin/env bash
# Sync Antigravity (Gemini) config from dotfiles SSOT to dotfiles/.gemini/ generated targets.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json
#   - $DOT_DIR/AGENTS.md
#   - $DOT_DIR/.agents/skills/
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.gemini/config/rules/shared-agents.md
#   - $DOT_DIR/.gemini/config/mcp_config.json
#
# Check mode (no write):
#   bash etc/sync-antigravity.sh --check

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"
GEMINI_DIR="${DOT_DIR}/.gemini"
GEMINI_CONFIG_DIR="${GEMINI_DIR}/config"
GEMINI_RULES_DIR="${GEMINI_CONFIG_DIR}/rules"
GEMINI_MCP="${GEMINI_CONFIG_DIR}/mcp_config.json"
GEMINI_RULE="${GEMINI_RULES_DIR}/shared-agents.md"

CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    -h|--help)
      sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "[sync-antigravity] unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

log()  { echo "[sync-antigravity] $*"; }
warn() { echo "[sync-antigravity] warn: $*" >&2; }
die()  { echo "[sync-antigravity] error: $*" >&2; exit 1; }

if ! command -v jq >/dev/null 2>&1; then
  warn "required dependency missing: jq"
  exit 1
fi

jq() { command jq "$@" | tr -d '\r'; }

if [ ! -f "$MCP_SRC" ]; then warn "required SSOT missing: $MCP_SRC"; exit 1; fi
if [ ! -f "$AGENTS_SRC" ]; then warn "required SSOT missing: $AGENTS_SRC"; exit 1; fi

reject_unsafe_target() {
  local dest="$1"
  if [ -L "$dest" ] || [ -d "$dest" ]; then
    die "refusing to publish generated output to symlink or directory: $dest"
  fi
}

reject_unsafe_target "$GEMINI_RULE"
reject_unsafe_target "$GEMINI_MCP"

if [ "$CHECK_ONLY" = "0" ]; then
  mkdir -p "$GEMINI_RULES_DIR"
fi

atomic_write() {
  local dest="$1" tmp="$2"
  reject_unsafe_target "$dest"
  if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    rm -f "$tmp"
    log "unchanged $dest"
    return 0
  fi
  if ! mv -f "$tmp" "$dest"; then
    rm -f "$tmp"
    die "failed to publish generated output: $dest"
  fi
  log "wrote $dest"
}

render_shared_rule() {
  cat <<'RULE_EOF'
<!-- AUTO-GENERATED by dotfiles/etc/sync-antigravity.sh; edit AGENTS.md instead -->

# Shared Guidance (Antigravity)

- **SSOT**: repository root `AGENTS.md` (and project overrides if present). Do **not** treat this rule as a full copy of AGENTS.md.
- Follow portable rules in `AGENTS.md`: Japanese output, no fabricated tool results, no `git add -A`, no unsolicited `git restore` / hard reset, minimal scope, `uv` for Python; **no ad-hoc fixes, no symptom-only patches, no over-engineering, no excessive contracts** (root cause first, smallest correct diff).
- Memory: auto-activate `/ai-ltm` (session start / resume / durable learnings) and `/field-notes` (campaign recall / decision capture) per `AGENTS.md`.
- Skills: Shared skills live in `.agents/skills/`.
RULE_EOF
}

build_mcp_json() {
  # Exclude other-runtime-only servers. Convert type:remote -> serverUrl
  # (Antigravity MCP schema uses serverUrl for SSE transport).
  jq '
    .mcpServers
    | with_entries(
        select(.value.claudeCodeOnly != true)
        | select(.value.openCodeOnly != true)
        | select(.value.codexOnly != true)
        | select(.value.cursorOnly != true)
        | .value |= (
            del(.claudeCodeOnly, .openCodeOnly, .codexOnly, .cursorOnly, .type)
            | if ((.url // "") | length > 0) and (.command | not) then
                { serverUrl: .url }
              else
                {
                  command: .command,
                  args: (.args // [])
                }
                + (if (.env // {}) | length > 0 then { env: .env } else {} end)
              end
          )
      )
    | { mcpServers: ., _generated_by: "dotfiles/etc/sync-antigravity.sh" }
  ' "$MCP_SRC"
}

write_shared_rule() {
  if [ "$CHECK_ONLY" = "1" ]; then
    local tmp
    tmp="$(mktemp)"
    render_shared_rule >"$tmp"
    if [ ! -f "$GEMINI_RULE" ] || ! cmp -s "$tmp" "$GEMINI_RULE"; then
      rm -f "$tmp"
      die "check failed: $GEMINI_RULE would change (or is missing)"
    fi
    rm -f "$tmp"
    log "check ok $GEMINI_RULE"
    return 0
  fi
  local tmp
  tmp="$(mktemp "${GEMINI_RULE}.tmp.XXXXXX")"
  if ! render_shared_rule >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $GEMINI_RULE"
  fi
  atomic_write "$GEMINI_RULE" "$tmp"
}

write_mcp_json() {
  local rendered tmp
  if ! rendered="$(build_mcp_json)"; then
    die "failed to generate $GEMINI_MCP"
  fi
  if [ "$CHECK_ONLY" = "1" ]; then
    if [ ! -f "$GEMINI_MCP" ]; then
      die "check failed: $GEMINI_MCP missing"
    fi
    if ! jq -e '._generated_by == "dotfiles/etc/sync-antigravity.sh"' "$GEMINI_MCP" >/dev/null 2>&1; then
      die "check failed: $GEMINI_MCP missing _generated_by marker"
    fi
    if [ "$(printf "%s" "$rendered" | jq -S .)" != "$(jq -S . "$GEMINI_MCP")" ]; then
      die "check failed: $GEMINI_MCP would change"
    fi
    log "check ok $GEMINI_MCP"
    return 0
  fi
  if [ -f "$GEMINI_MCP" ] && ! jq -e '._generated_by == "dotfiles/etc/sync-antigravity.sh"' "$GEMINI_MCP" >/dev/null 2>&1; then
    warn "refusing to overwrite hand-edited $GEMINI_MCP (missing _generated_by marker)"
    return 0
  fi
  tmp="$(mktemp "${GEMINI_MCP}.tmp.XXXXXX")"
  if ! printf "%s\n" "$rendered" >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $GEMINI_MCP"
  fi
  atomic_write "$GEMINI_MCP" "$tmp"
}

write_shared_rule
write_mcp_json

# Ensure hooks and scripts exist in dotfiles/.gemini/config
if [ ! -f "${GEMINI_CONFIG_DIR}/hooks.json" ]; then
  warn "missing ${GEMINI_CONFIG_DIR}/hooks.json"
fi
if [ ! -f "${GEMINI_CONFIG_DIR}/scripts/auto-gate.py" ]; then
  warn "missing ${GEMINI_CONFIG_DIR}/scripts/auto-gate.py"
elif [ "$CHECK_ONLY" = "0" ]; then
  chmod +x "${GEMINI_CONFIG_DIR}/scripts/auto-gate.py" 2>/dev/null || true
fi

# Ensure skills symlink exists inside dotfiles/.gemini/config
GEMINI_SKILLS_DIR="${GEMINI_CONFIG_DIR}/skills"
SHARED_SKILLS_DIR="${DOT_DIR}/.agents/skills"
if [ -d "$SHARED_SKILLS_DIR" ]; then
  if [ "$CHECK_ONLY" = "1" ]; then
    [ -d "$GEMINI_SKILLS_DIR" ] || die "check failed: $GEMINI_SKILLS_DIR missing or dangling"
    [ "$(cd -P "$GEMINI_SKILLS_DIR" && pwd)" = "$(cd -P "$SHARED_SKILLS_DIR" && pwd)" ] || die "check failed: $GEMINI_SKILLS_DIR does not resolve to shared skills"
  elif [ ! -e "$GEMINI_SKILLS_DIR" ] && [ ! -L "$GEMINI_SKILLS_DIR" ]; then
    ln -s "../../.agents/skills" "$GEMINI_SKILLS_DIR"
    log "linked $GEMINI_SKILLS_DIR -> ../../.agents/skills"
  elif [ ! -d "$GEMINI_SKILLS_DIR" ]; then
    die "refusing to replace existing non-directory or dangling link: $GEMINI_SKILLS_DIR"
  elif [ "$(cd -P "$GEMINI_SKILLS_DIR" && pwd)" != "$(cd -P "$SHARED_SKILLS_DIR" && pwd)" ]; then
    die "refusing to replace existing skills with a different target: $GEMINI_SKILLS_DIR"
  fi
fi

if [ "$CHECK_ONLY" = "1" ]; then
  log "check passed"
  exit 0
fi

log "done"
