#!/usr/bin/env bash
# Sync Cursor config from dotfiles SSOT to dotfiles/.cursor/ generated targets.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json
#   - $DOT_DIR/AGENTS.md
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.cursor/rules/shared-agents.mdc   (summary + pointer; NOT full AGENTS.md)
#   - $DOT_DIR/.cursor/mcp.json
#
# Native overlay (NOT regenerated by default):
#   - $DOT_DIR/.cursor/agents/**
#   - $DOT_DIR/.cursor/skills/**
#
# Seed (explicit only):
#   SYNC_CURSOR_SEED=1 bash etc/sync-cursor.sh
#   # or: bash etc/seed-cursor-overlay.sh
#
# Check mode (no write):
#   bash etc/sync-cursor.sh --check

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"
CURSOR_DIR="${DOT_DIR}/.cursor"
CURSOR_RULES_DIR="${CURSOR_DIR}/rules"
CURSOR_MCP="${CURSOR_DIR}/mcp.json"
CURSOR_RULE="${CURSOR_RULES_DIR}/shared-agents.mdc"

CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    -h|--help)
      sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "[sync-cursor] unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

log()  { echo "[sync-cursor] $*"; }
warn() { echo "[sync-cursor] warn: $*" >&2; }
die()  { echo "[sync-cursor] error: $*" >&2; exit 1; }

if ! command -v jq >/dev/null 2>&1; then
  warn "required dependency missing: jq"
  exit 1
fi

jq() { command jq "$@" | tr -d '\r'; }

if [ ! -f "$MCP_SRC" ]; then warn "required SSOT missing: $MCP_SRC"; exit 1; fi
if [ ! -f "$AGENTS_SRC" ]; then warn "required SSOT missing: $AGENTS_SRC"; exit 1; fi

reject_unsafe_target() {
  local dest="$1"
  if [ -L "$dest" ] || [ -d "$dest" ]; then
    die "refusing to publish generated output to symlink or directory: $dest"
  fi
}

reject_unsafe_target "$CURSOR_RULE"
reject_unsafe_target "$CURSOR_MCP"

if [ "$CHECK_ONLY" = "0" ]; then
  mkdir -p "$CURSOR_RULES_DIR"
fi

atomic_write() {
  # atomic_write <dest> <complete_tmp>
  local dest="$1" tmp="$2"
  reject_unsafe_target "$dest"
  if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    rm -f "$tmp"
    log "unchanged $dest"
    return 0
  fi
  if ! mv -f "$tmp" "$dest"; then
    rm -f "$tmp"
    die "failed to publish generated output: $dest"
  fi
  log "wrote $dest"
}

render_shared_rule() {
  # Design A: summary + pointer. Do not embed full AGENTS.md (avoids double-load with repo AGENTS.md).
  cat <<'EOF'
---
description: Shared AI agent guidance pointer (SSOT is repo AGENTS.md)
alwaysApply: true
---

<!-- AUTO-GENERATED by dotfiles/etc/sync-cursor.sh; edit AGENTS.md instead -->

# Shared guidance (Cursor)

- **SSOT**: repository root `AGENTS.md`, especially its `Execution And Skill Priority` section (and project overrides if present). Do **not** treat this rule as a full copy of AGENTS.md.
- Follow portable rules in `AGENTS.md`: Japanese output, no fabricated tool results, no `git add -A`, no unsolicited `git restore` / hard reset, minimal scope, `uv` for Python; **no ad-hoc fixes, no symptom-only patches, no over-engineering, no excessive contracts** (root cause first, smallest correct diff; do not grow closure/oracle fingerprint chains without a contract-shaped failure).
- Memory: auto-activate `/ai-ltm` (session start / resume / durable learnings) and `/field-notes` (campaign recall / decision capture) per `AGENTS.md` — do not double-write
- Architecture: shared core + native overlays — see `AI-WORKFLOW-SPEC.md`. Cursor overlays live in `.cursor/agents` and `.cursor/skills`.
- Runtime mechanics for Cursor (Task / Skills / subagents) belong in `.cursor/**`, not in Claude-only paths.
- Execution: continue permitted, executable implementation and verification to completion; prepare independent permitted work and reviewable artifacts before requesting required approval.
- Priority and reporting: preserve higher-level instructions and actual access controls, while explicit user instructions take precedence over Skill advice. If a Skill causes a permission/confirmation request, a pause, incomplete work, or a change of direction, report the actually read `SKILL.md` path as a link, quoted rule, interpretation and reason, environment constraint, completed preparation, and required operation; never disclose secrets, non-public higher-level instructions, or internal reasoning.
- Verification and sources: choose verification proportional to concrete harm. Use the official `openai-docs` Skill when available, otherwise primary official sources; do not make additional authentication mandatory.
- Measurement: use existing task reports and runtime logs to compare parent direct work and delegation under the same acceptance criteria; record elapsed time, rework, and available usage, including parent preparation, checks, and retries. Do not treat unmeasured values as zero or infer costs; no new ledger or runner schema.
- Model policy: Cursor agent `model` is `inherit` or a real model ID. Job class is `role: coding|reasoning` (not `model`).
- **Task `model`**: omit or `inherit` only (follow parent Auto). Do not pass vendor slugs (`opus` / `sonnet` / `claude-*` / `cursor-grok-*`, etc.) unless the user explicitly names a model. **Named exception**: `/deepthink` and `/deepplan` must pass `claude-fable-5-1[effort=…]` on Task for `deliberator` / `synthesizer` / `gate` only (default effort `medium`; keep those agents' Cursor frontmatter as `inherit` and override at Task launch).

When working inside the `dotfiles` repo, prefer the checked-out `AGENTS.md` over expanding this summary.
EOF
}

build_mcp_json() {
  # Exclude other-runtime-only servers. Convert type:remote → url-only
  # (Cursor CLI may drop the whole file on unknown MCP entry types).
  jq '
    .mcpServers
    | with_entries(
        select(.value.claudeCodeOnly != true)
        | select(.value.openCodeOnly != true)
        | select(.value.codexOnly != true)
        | .value |= (
            del(.claudeCodeOnly, .openCodeOnly, .codexOnly, .cursorOnly)
            | if .type == "remote" then
                { url: .url }
                + (if (.headers // {}) | length > 0 then { headers: .headers } else {} end)
              elif ((.url // "") | length > 0) and (.command | not) then
                { url: .url }
                + (if (.headers // {}) | length > 0 then { headers: .headers } else {} end)
              else
                {
                  command: .command,
                  args: (.args // [])
                }
                + (if (.env // {}) | length > 0 then { env: .env } else {} end)
              end
          )
      )
    | { mcpServers: ., _generated_by: "dotfiles/etc/sync-cursor.sh" }
  ' "$MCP_SRC"
}

write_shared_rule() {
  if [ "$CHECK_ONLY" = "1" ]; then
    local tmp expected
    tmp="$(mktemp)"
    render_shared_rule >"$tmp"
    if [ ! -f "$CURSOR_RULE" ] || ! cmp -s "$tmp" "$CURSOR_RULE"; then
      rm -f "$tmp"
      die "check failed: $CURSOR_RULE would change (or is missing)"
    fi
    rm -f "$tmp"
    log "check ok $CURSOR_RULE"
    return 0
  fi
  local tmp
  tmp="$(mktemp "${CURSOR_RULE}.tmp.XXXXXX")"
  if ! render_shared_rule >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $CURSOR_RULE"
  fi
  atomic_write "$CURSOR_RULE" "$tmp"
}

write_mcp_json() {
  local rendered tmp
  if ! rendered="$(build_mcp_json)"; then
    die "failed to generate $CURSOR_MCP"
  fi
  if [ "$CHECK_ONLY" = "1" ]; then
    if [ ! -f "$CURSOR_MCP" ]; then
      die "check failed: $CURSOR_MCP missing"
    fi
    if ! jq -e '._generated_by == "dotfiles/etc/sync-cursor.sh"' "$CURSOR_MCP" >/dev/null 2>&1; then
      die "check failed: $CURSOR_MCP missing _generated_by marker"
    fi
    if [ "$(printf '%s' "$rendered" | jq -S .)" != "$(jq -S . "$CURSOR_MCP")" ]; then
      die "check failed: $CURSOR_MCP would change"
    fi
    log "check ok $CURSOR_MCP"
    return 0
  fi
  if [ -f "$CURSOR_MCP" ] && ! jq -e '._generated_by == "dotfiles/etc/sync-cursor.sh"' "$CURSOR_MCP" >/dev/null 2>&1; then
    warn "refusing to overwrite hand-edited $CURSOR_MCP (missing _generated_by marker)"
    return 0
  fi
  tmp="$(mktemp "${CURSOR_MCP}.tmp.XXXXXX")"
  if ! printf '%s\n' "$rendered" >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $CURSOR_MCP"
  fi
  atomic_write "$CURSOR_MCP" "$tmp"
}

write_shared_rule
write_mcp_json

if [ "$CHECK_ONLY" = "1" ]; then
  log "check passed"
  exit 0
fi

if [ "${SYNC_CURSOR_SEED:-}" = "1" ]; then
  bash "${SCRIPT_DIR}/seed-cursor-overlay.sh"
fi

log "done"
