#!/usr/bin/env bash
# Sync Cursor config from dotfiles SSOT to dotfiles/.cursor/ generated targets.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json
#   - $DOT_DIR/.agents/global-instructions.md
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.cursor/rules/shared-agents.mdc   (always-applied common instructions)
#   - $DOT_DIR/.cursor/mcp.json
#
# Native overlay (hand-written, never regenerated):
#   - $DOT_DIR/.cursor/agents/**
#   - $DOT_DIR/.cursor/skills/**  (Cursor-specific overlays and Cursor-only skills;
#     shared skills are discovered from ~/.agents/skills)
#
# Check mode (no write):
#   bash etc/sync-cursor.sh --check

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
GLOBAL_INSTRUCTIONS_SRC="${DOT_DIR}/.agents/global-instructions.md"
CURSOR_DIR="${DOT_DIR}/.cursor"
CURSOR_RULES_DIR="${CURSOR_DIR}/rules"
CURSOR_MCP="${CURSOR_DIR}/mcp.json"
CURSOR_RULE="${CURSOR_RULES_DIR}/shared-agents.mdc"

CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "[sync-cursor] unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

log()  { echo "[sync-cursor] $*"; }
warn() { echo "[sync-cursor] warn: $*" >&2; }
die()  { echo "[sync-cursor] error: $*" >&2; exit 1; }

if ! command -v jq >/dev/null 2>&1; then
  warn "required dependency missing: jq"
  exit 1
fi

jq() { command jq "$@" | tr -d '\r'; }

if [ ! -f "$MCP_SRC" ]; then warn "required SSOT missing: $MCP_SRC"; exit 1; fi
if [ ! -f "$GLOBAL_INSTRUCTIONS_SRC" ]; then warn "required SSOT missing: $GLOBAL_INSTRUCTIONS_SRC"; exit 1; fi

reject_unsafe_target() {
  local dest="$1"
  if [ -L "$dest" ] || [ -d "$dest" ]; then
    die "refusing to publish generated output to symlink or directory: $dest"
  fi
}

reject_unsafe_target "$CURSOR_RULE"
reject_unsafe_target "$CURSOR_MCP"

if [ "$CHECK_ONLY" = "0" ]; then
  mkdir -p "$CURSOR_RULES_DIR"
fi

atomic_write() {
  # atomic_write <dest> <complete_tmp>
  local dest="$1" tmp="$2"
  reject_unsafe_target "$dest"
  if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    rm -f "$tmp"
    log "unchanged $dest"
    return 0
  fi
  if ! mv -f "$tmp" "$dest"; then
    rm -f "$tmp"
    die "failed to publish generated output: $dest"
  fi
  log "wrote $dest"
}

render_shared_rule() {
  cat <<'EOF'
---
description: Shared AI agent guidance from the global instructions source
alwaysApply: true
---

<!-- AUTO-GENERATED by dotfiles/etc/sync-cursor.sh from .agents/global-instructions.md; edit the source instead -->
EOF
  cat "$GLOBAL_INSTRUCTIONS_SRC"
}

build_mcp_json() {
  # Exclude other-runtime-only servers. Convert type:remote → url-only
  # (Cursor CLI may drop the whole file on unknown MCP entry types).
  jq '
    .mcpServers
    | with_entries(
        select(.value.claudeCodeOnly != true)
        | select(.value.openCodeOnly != true)
        | select(.value.codexOnly != true)
        | select(.value.devinOnly != true)
        | .value |= (
            del(.claudeCodeOnly, .openCodeOnly, .codexOnly, .cursorOnly, .devinOnly)
            | if .type == "remote" then
                { url: .url }
                + (if (.headers // {}) | length > 0 then { headers: .headers } else {} end)
              elif ((.url // "") | length > 0) and (.command | not) then
                { url: .url }
                + (if (.headers // {}) | length > 0 then { headers: .headers } else {} end)
              else
                {
                  command: .command,
                  args: (.args // [])
                }
                + (if (.env // {}) | length > 0 then { env: .env } else {} end)
              end
          )
      )
    | { mcpServers: ., _generated_by: "dotfiles/etc/sync-cursor.sh" }
  ' "$MCP_SRC"
}

write_shared_rule() {
  if [ "$CHECK_ONLY" = "1" ]; then
    local tmp expected
    tmp="$(mktemp)"
    render_shared_rule >"$tmp"
    if [ ! -f "$CURSOR_RULE" ] || ! cmp -s "$tmp" "$CURSOR_RULE"; then
      rm -f "$tmp"
      die "check failed: $CURSOR_RULE would change (or is missing)"
    fi
    rm -f "$tmp"
    log "check ok $CURSOR_RULE"
    return 0
  fi
  local tmp
  tmp="$(mktemp "${CURSOR_RULE}.tmp.XXXXXX")"
  if ! render_shared_rule >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $CURSOR_RULE"
  fi
  atomic_write "$CURSOR_RULE" "$tmp"
}

write_mcp_json() {
  local rendered tmp
  if ! rendered="$(build_mcp_json)"; then
    die "failed to generate $CURSOR_MCP"
  fi
  if [ "$CHECK_ONLY" = "1" ]; then
    if [ ! -f "$CURSOR_MCP" ]; then
      die "check failed: $CURSOR_MCP missing"
    fi
    if ! jq -e '._generated_by == "dotfiles/etc/sync-cursor.sh"' "$CURSOR_MCP" >/dev/null 2>&1; then
      die "check failed: $CURSOR_MCP missing _generated_by marker"
    fi
    if [ "$(printf '%s' "$rendered" | jq -S .)" != "$(jq -S . "$CURSOR_MCP")" ]; then
      die "check failed: $CURSOR_MCP would change"
    fi
    log "check ok $CURSOR_MCP"
    return 0
  fi
  if [ -f "$CURSOR_MCP" ] && ! jq -e '._generated_by == "dotfiles/etc/sync-cursor.sh"' "$CURSOR_MCP" >/dev/null 2>&1; then
    warn "refusing to overwrite hand-edited $CURSOR_MCP (missing _generated_by marker)"
    return 0
  fi
  tmp="$(mktemp "${CURSOR_MCP}.tmp.XXXXXX")"
  if ! printf '%s\n' "$rendered" >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate $CURSOR_MCP"
  fi
  atomic_write "$CURSOR_MCP" "$tmp"
}

write_shared_rule
write_mcp_json

if [ "$CHECK_ONLY" = "1" ]; then
  python3 "${DOT_DIR}/jev-hooks/install.py" cursor --check
  python3 "${DOT_DIR}/etc/install-session-sync-hook.py" cursor --check
else
  python3 "${DOT_DIR}/jev-hooks/install.py" cursor
  python3 "${DOT_DIR}/etc/install-session-sync-hook.py" cursor
fi

if [ "$CHECK_ONLY" = "1" ]; then
  log "check passed"
  exit 0
fi

log "done"
