#!/usr/bin/env bash
# Sync Codex config from dotfiles SSOT to dotfiles/.codex/.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json          (MCP servers)
#   - $DOT_DIR/.claude/CLAUDE.md         (global instructions)
#   - $DOT_DIR/.claude/format.md         (referenced instructions)
#   - $DOT_DIR/.claude/pir-handoff.md    (referenced instructions)
#   - $DOT_DIR/.claude/user-feedback-protocol.md (referenced instructions)
#   - $DOT_DIR/.claude/agent-delegation.md     (referenced instructions)
#   - $DOT_DIR/.claude/pir2-protocol.md        (referenced instructions)
#   - $DOT_DIR/.claude/dev-server.md           (referenced instructions)
#   - $DOT_DIR/.claude/subagent-permissions.md (referenced instructions)
#   - $DOT_DIR/.claude/agents/*.md       (agent definitions, mirrored)
#   - $DOT_DIR/.claude/skills/*          (skill definitions, mirrored)
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.codex/config.toml
#   - $DOT_DIR/.codex/AGENTS.md
#   - $DOT_DIR/.codex/format.md
#   - $DOT_DIR/.codex/pir-handoff.md
#   - $DOT_DIR/.codex/user-feedback-protocol.md
#   - $DOT_DIR/.codex/agent-delegation.md
#   - $DOT_DIR/.codex/pir2-protocol.md
#   - $DOT_DIR/.codex/dev-server.md
#   - $DOT_DIR/.codex/subagent-permissions.md
#   - $DOT_DIR/.codex/agents/<name>.md
#   - $DOT_DIR/.codex/skills/<name>/
#
# Re-running is idempotent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
CLAUDE_DIR="${DOT_DIR}/.claude"
CODEX_DIR="${DOT_DIR}/.codex"
CODEX_BASE_CONFIG="${CODEX_DIR}/config.base.toml"
CODEX_CONFIG="${CODEX_DIR}/config.toml"
CODEX_AGENTS_DIR="${CODEX_DIR}/agents"
CODEX_SKILLS_DIR="${CODEX_DIR}/skills"

log()  { echo "[sync-codex] $*"; }
warn() { echo "[sync-codex] warn: $*" >&2; }

if ! command -v jq >/dev/null 2>&1; then
  warn "jq not found, skipping sync"
  exit 0
fi

# Windows-native jq emits CRLF line terminators, which leak \r into generated
# TOML keys/values (e.g. [mcp_servers."codex\r"]) and break key matching.
# Wrap jq to strip CR from its output so generation is byte-clean on any OS.
# Defined AFTER the availability check above so `command -v jq` still tests the
# real binary, not this function.
jq() { command jq "$@" | tr -d '\r'; }

if [ ! -f "$MCP_SRC" ]; then warn "missing $MCP_SRC"; exit 0; fi
if [ ! -f "$CODEX_BASE_CONFIG" ]; then warn "missing $CODEX_BASE_CONFIG"; exit 0; fi

mkdir -p "$CODEX_DIR" "$CODEX_AGENTS_DIR" "$CODEX_SKILLS_DIR"

toml_quote() {
  jq -Rn --arg s "$1" '$s'
}

toml_array() {
  jq -c '.' | sed 's/,/, /g'
}

build_hooks_section_toml() {
  echo
  echo "# ---- AUTO-GENERATED hooks (dotfiles SSOT) ----"
  echo "[features]"
  # Codex 公式の現行フラグは `hooks = true`（`codex_hooks` は deprecated alias）
  echo "hooks = true"
  echo
  echo "[[hooks.PostToolUse]]"
  echo 'matcher = "Edit|Write|MultiEdit"'
  echo
  echo "[[hooks.PostToolUse.hooks]]"
  echo 'type = "command"'
  printf 'command = %s\n' "$(toml_quote "bash ${DOT_DIR}/etc/sync-codex.sh")"
}

write_codex_config() {
  # Guard: 既存 config.toml が AUTO-GENERATED ヘッダを持たない場合は手書きと見なし保護する
  if [ -f "$CODEX_CONFIG" ] && ! head -1 "$CODEX_CONFIG" | grep -q '^# AUTO-GENERATED by dotfiles/etc/sync-codex.sh'; then
    warn "refusing to overwrite hand-edited $CODEX_CONFIG (no AUTO-GENERATED header)"
    warn "remove the file or restore the header to enable sync"
    return 0
  fi

  local tmp toml_err
  tmp="$(mktemp "${CODEX_DIR}/config.toml.tmp.XXXXXX")"

  {
    echo "# AUTO-GENERATED by dotfiles/etc/sync-codex.sh from SSOT."
    echo "# Edit .codex/config.base.toml or the Claude-side SSOT files instead."

    echo
    cat "$CODEX_BASE_CONFIG"
    echo
    echo "# ---- AUTO-GENERATED MCP servers from mcp-servers.json ----"

    jq -r '.mcpServers | keys[]' "$MCP_SRC" | while IFS= read -r name; do
      local server type table_name command args env_json env_rendered url
      server="$(jq -c --arg name "$name" '.mcpServers[$name]' "$MCP_SRC")"

      if [ "$(printf '%s' "$server" | jq -r '.codexOnly // false')" = "false" ] &&
         { [ "$(printf '%s' "$server" | jq -r '.claudeCodeOnly // false')" = "true" ] ||
           [ "$(printf '%s' "$server" | jq -r '.openCodeOnly // false')" = "true" ]; }; then
        continue
      fi

      table_name="$(toml_quote "$name")"
      type="$(printf '%s' "$server" | jq -r '.type // (if .url then "remote" else "local" end)')"

      echo
      printf '[mcp_servers.%s]\n' "$table_name"
      echo "enabled = true"

      if [ "$type" = "remote" ]; then
        url="$(printf '%s' "$server" | jq -r '.url // empty')"
        if [ -z "$url" ]; then
          warn "remote MCP server '$name' has no url, skipping"
          continue
        fi
        printf 'url = %s\n' "$(toml_quote "$url")"
        if printf '%s' "$server" | jq -e '.bearer_token_env_var? // empty' >/dev/null; then
          printf 'bearer_token_env_var = %s\n' "$(toml_quote "$(printf '%s' "$server" | jq -r '.bearer_token_env_var')")"
        fi
      else
        command="$(printf '%s' "$server" | jq -r '.command // empty')"
        if [ -z "$command" ]; then
          warn "local MCP server '$name' has no command, skipping"
          continue
        fi
        args="$(printf '%s' "$server" | jq '.args // []' | toml_array)"
        printf 'command = %s\n' "$(toml_quote "$command")"
        printf 'args = %s\n' "$args"

        env_json="$(printf '%s' "$server" | jq -c '.env // {}')"
        if [ "$(printf '%s' "$env_json" | jq 'length')" != "0" ]; then
          # Note: rendered into an intermediate variable to avoid bash 3.2's
          # brace-expansion bug, where literal '{ ... , ... }' inside a single-
          # quoted filter nested in "$(...)" gets mis-expanded into two words.
          env_rendered="$(printf '%s' "$env_json" | jq -r 'to_entries | map("\(.key) = \(.value | @json)") | "{ " + join(", ") + " }"')"
          printf 'env = %s\n' "$env_rendered"
        fi
      fi
    done

    build_hooks_section_toml
  } > "$tmp"

  # TOML 構文検証（python3 が利用可能な場合のみ）
  if command -v python3 >/dev/null 2>&1; then
    if ! toml_err="$(python3 -c 'import sys, tomllib; tomllib.load(open(sys.argv[1], "rb"))' "$tmp" 2>&1)"; then
      warn "generated TOML is invalid, aborting (tmp: $tmp)"
      warn "python3 error: $toml_err"
      return 1
    fi
  else
    warn "python3 not found, skipping TOML syntax validation"
  fi

  mv -f "$tmp" "$CODEX_CONFIG"
  log "wrote $CODEX_CONFIG"
}

copy_with_header() {
  local src="$1" dst="$2" label="$3"
  [ -f "$src" ] || return 0
  {
    printf '<!-- AUTO-GENERATED by etc/sync-codex.sh from %s. Do not edit. -->\n\n' "$label"
    cat "$src"
  } > "$dst"
  log "wrote $dst"
}

build_codex_agents_md() {
  local src="${CLAUDE_DIR}/CLAUDE.md"
  local dst="${CODEX_DIR}/AGENTS.md"
  [ -f "$src" ] || return 0

  {
    cat <<'HEADER'
<!-- AUTO-GENERATED by etc/sync-codex.sh from .claude/CLAUDE.md.
     Do not edit by hand. Re-run: bash etc/sync-codex.sh
     Codex reads AGENTS.md; this file keeps the Claude Code SSOT plus Codex-specific compatibility rules. -->

HEADER
    cat "$src"
    cat <<'FOOTER'

---

# Codex 専用補足ルール（dotfiles SSOT 由来）

このセクションは Codex 起動時にのみ効く。Claude Code 環境では `~/.claude/CLAUDE.md` が SSOT であり、この `.codex/AGENTS.md` は読まれない。

## 相互運用の基本方針

- `.claude/` を運用ルールの SSOT とし、`.codex/` は Codex 用の生成物と互換レイヤーとして扱う
- `.claude` 側のルールを Codex で読むときは、下の読み替え表を必ず適用する
- `.codex` 側の自動生成ファイルを手編集しない。恒久変更は `.claude` 側の SSOT か `etc/sync-codex.sh` に入れる
- Codex では、Claude Code 固有機能が使えないことを理由に作業を止めない。意味が保てる場合は Codex の実ツールで同等の手順に落とす

## Claude Code 固有表記の読み替え

| Claude Code 側の表記 | Codex での扱い |
|---------------------|---------------|
| `Agent` ツール / `Agent` で `<role>` を起動 | Codex セッションに sub-agent tool が提供されている場合のみ同等ロールで起動する。提供されていない、またはツール制約上起動できない場合は、メイン Codex が該当ロールの観点を直接適用する |
| `Skill` ツールでスキルを呼び出す | Codex の skill trigger に従う。明示起動されたスキルは `SKILL.md` を読んで、実行可能な部分をメイン Codex が実行する |
| `TeamCreate` / Agent Teams | Codex では前提にしない。`/pir2async` は概念参照のみとし、実行が必要なら通常の順次/並列 sub-agent かメイン Codex の直接作業に縮退する |
| `haiku` / `sonnet` / `opus` / `claude-sonnet-4-6` | Codex の現在モデルを既定にする。sub-agent tool がモデル指定を受け付ける場合のみ、利用可能な Codex モデルへ保守的に置き換える |
| `Glob` / `Grep` / `Read` / `Edit` / `Write` / `Bash` | Codex の `rg` / shell / filesystem / `apply_patch` 等の実ツールに置き換える |
| `WebSearch` / `WebFetch` | Codex の web search、Brave、Context7 等、利用可能な一次ソース確認ツールに置き換える |
| `mcp__codex__codex` への相談 | Codex 自身からの自己相談ルールとしては無効。無視する |
| `~/.claude/<file>` 参照 | Codex で読むときは、存在すれば対応する `.codex/<file>` を優先する。SSOT を編集するときだけ `.claude/<file>` を編集する |
| `~/.claude/projects/<sanitized>/memory` | Claude Code の長期記憶領域。Codex から参照する場合は読み取り中心にし、新しい Codex 専用記録は明示された保存先がない限り増やさない |

## Codex でのワークフロー運用

- `/pir2`, `/debug`, `/ir`, `/writing-plan` は Claude Code の `Agent` オーケストレーションを逐語実行しない。Codex では **Plan → Implement → Review → Test** の意味を保ち、メイン Codex が直接進める
- `/reviewer`, `/review-pr`, `/tester`, `/refactor-advisor`, `/sentinel-review` は、専用 sub-agent が使える場合は使ってよい。使えない場合はメイン Codex が同じ観点でレビュー/検証する
- `/brainstorm`, `/chat`, `/walkthrough`, `/ai-diary`, `/ai-ltm`, `/check-updates`, `/skill-creator`, `/plugin-creator` は Codex でも使用可能。ただしスキル内の `Agent`/`Skill` 表記は上記の読み替えを適用する
- `/pir2async` は Agent Teams 前提の実験版なので、Codex では非推奨。必要な場合は `/pir2` 相当の順次フローに縮退する
- reviewer の 5 観点（correctness / consistency / quality / security / architecture）は Codex でも維持する。ただし必ず 5 体を起動するのではなく、変更リスクに応じてメイン Codex が観点を選ぶ

## 探索委譲ルールの Codex 版

Claude Code 側では広域探索を explorer に委譲するが、Codex では sub-agent tool の有無に依存する。

1. sub-agent tool があり、ユーザー指示や現在のツール制約が許す場合は explorer 相当を起動する
2. それ以外は、メイン Codex が `rg` / `rg --files` / `git diff` / 必要なファイル Read で探索する
3. どちらの場合も、探索結果の事実と推測を分けて扱い、未確認の前提で実装しない
4. 既存パターン逸脱・リファレンス移植・ライブラリ選定などのゲートは Codex でも維持する

## 権限と編集

- `.codex/config.toml` は `etc/sync-codex.sh` 生成物。設定変更は `.codex/config.base.toml` または `mcp-servers.json` に入れる
- `.codex/agents/` と `.codex/skills/` は原則 `.claude/` からの mirror。Codex 専用の永続差分が必要になったら、生成スクリプト側に変換規則として入れる
- Claude Code の `.claude/settings.json` の allow/deny は Codex にそのまま適用されない。Codex では `sandbox_mode` / approval / filesystem sandbox の実効ルールを優先する
FOOTER
  } > "$dst"

  log "wrote $dst"
}

quote_yaml_scalar() {
  local raw="$1"
  local decoded="$raw"

  case "$raw" in
    \"*\")
      decoded="$(printf '%s' "$raw" | jq -r . 2>/dev/null || printf '%s' "$raw")"
      ;;
  esac

  printf '%s' "$decoded" | jq -Rs .
}

normalize_codex_skill_frontmatter() {
  local file="$1"
  [ -f "$file" ] || return 0

  local tmp
  tmp="$(mktemp "${file}.tmp.XXXXXX")"

  local fence_count=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "---" ]; then
      fence_count=$((fence_count + 1))
      printf '%s\n' "$line" >> "$tmp"
      continue
    fi

    if [ "$fence_count" -eq 1 ] && [[ "$line" =~ ^([A-Za-z0-9_-]+):[[:space:]]*(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      printf '%s: %s\n' "$key" "$(quote_yaml_scalar "$value")" >> "$tmp"
    else
      printf '%s\n' "$line" >> "$tmp"
    fi
  done < "$file"

  mv -f "$tmp" "$file"
}

sync_agents() {
  local src_dir="${CLAUDE_DIR}/agents"
  [ -d "$src_dir" ] || return 0

  for f in "$src_dir"/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "${CODEX_AGENTS_DIR}/$(basename "$f")" ".claude/agents/$(basename "$f")"
  done

  for f in "$CODEX_AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    if ! head -1 "$f" | grep -q '^<!-- AUTO-GENERATED by etc/sync-codex.sh'; then
      continue
    fi
    if [ ! -f "${src_dir}/$(basename "$f")" ]; then
      rm -f "$f"
      log "removed orphan agent: $(basename "$f")"
    fi
  done
}

sync_skills() {
  local src_dir="${CLAUDE_DIR}/skills"
  [ -d "$src_dir" ] || return 0

  for d in "$src_dir"/*; do
    [ -d "$d" ] || continue
    local name dst marker
    name="$(basename "$d")"
    dst="${CODEX_SKILLS_DIR}/${name}"
    marker="${dst}/.codex-generated-from-claude"

    if [ -e "$dst" ] && [ ! -f "$marker" ]; then
      warn "not overwriting non-generated skill: $dst"
      continue
    fi

    rm -rf "$dst"
    mkdir -p "$dst"
    cp -a "$d"/. "$dst"/
    rm -rf "$dst/.git"
    normalize_codex_skill_frontmatter "$dst/SKILL.md"
    touch "$marker"
    log "mirrored skill: $name"
  done

  for d in "$CODEX_SKILLS_DIR"/*; do
    [ -d "$d" ] || continue
    [ -f "$d/.codex-generated-from-claude" ] || continue
    if [ ! -d "${src_dir}/$(basename "$d")" ]; then
      rm -rf "$d"
      log "removed orphan skill: $(basename "$d")"
    fi
  done
}

write_codex_config
build_codex_agents_md
copy_with_header "${CLAUDE_DIR}/format.md" "${CODEX_DIR}/format.md" ".claude/format.md"
copy_with_header "${CLAUDE_DIR}/pir-handoff.md" "${CODEX_DIR}/pir-handoff.md" ".claude/pir-handoff.md"
copy_with_header "${CLAUDE_DIR}/user-feedback-protocol.md" "${CODEX_DIR}/user-feedback-protocol.md" ".claude/user-feedback-protocol.md"
copy_with_header "${CLAUDE_DIR}/agent-delegation.md" "${CODEX_DIR}/agent-delegation.md" ".claude/agent-delegation.md"
copy_with_header "${CLAUDE_DIR}/pir2-protocol.md" "${CODEX_DIR}/pir2-protocol.md" ".claude/pir2-protocol.md"
copy_with_header "${CLAUDE_DIR}/dev-server.md" "${CODEX_DIR}/dev-server.md" ".claude/dev-server.md"
copy_with_header "${CLAUDE_DIR}/subagent-permissions.md" "${CODEX_DIR}/subagent-permissions.md" ".claude/subagent-permissions.md"
sync_agents
sync_skills

log "done"
