#!/usr/bin/env bash
# Sync Codex config from dotfiles SSOT to dotfiles/.codex/.
#
# SSOT:
#   - $DOT_DIR/mcp-servers.json          (MCP servers)
#   - $DOT_DIR/.claude/CLAUDE.md         (global instructions)
#   - $DOT_DIR/.claude/format.md         (referenced instructions)
#   - $DOT_DIR/.claude/pir-handoff.md    (referenced instructions)
#   - $DOT_DIR/.claude/agents/*.md       (agent definitions, mirrored)
#   - $DOT_DIR/.claude/skills/*          (skill definitions, mirrored)
#
# Generated (AUTO-GENERATED, do not hand-edit):
#   - $DOT_DIR/.codex/config.toml
#   - $DOT_DIR/.codex/AGENTS.md
#   - $DOT_DIR/.codex/format.md
#   - $DOT_DIR/.codex/pir-handoff.md
#   - $DOT_DIR/.codex/agents/<name>.md
#   - $DOT_DIR/.codex/skills/<name>/
#
# Re-running is idempotent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

MCP_SRC="${DOT_DIR}/mcp-servers.json"
CLAUDE_DIR="${DOT_DIR}/.claude"
CODEX_DIR="${DOT_DIR}/.codex"
CODEX_BASE_CONFIG="${CODEX_DIR}/config.base.toml"
CODEX_CONFIG="${CODEX_DIR}/config.toml"
CODEX_AGENTS_DIR="${CODEX_DIR}/agents"
CODEX_SKILLS_DIR="${CODEX_DIR}/skills"

log()  { echo "[sync-codex] $*"; }
warn() { echo "[sync-codex] warn: $*" >&2; }

if ! command -v jq >/dev/null 2>&1; then
  warn "jq not found, skipping sync"
  exit 0
fi
if [ ! -f "$MCP_SRC" ]; then warn "missing $MCP_SRC"; exit 0; fi
if [ ! -f "$CODEX_BASE_CONFIG" ]; then warn "missing $CODEX_BASE_CONFIG"; exit 0; fi

mkdir -p "$CODEX_DIR" "$CODEX_AGENTS_DIR" "$CODEX_SKILLS_DIR"

toml_quote() {
  jq -Rn --arg s "$1" '$s'
}

toml_array() {
  jq -c '.' | sed 's/,/, /g'
}

write_codex_config() {
  # Guard: 既存 config.toml が AUTO-GENERATED ヘッダを持たない場合は手書きと見なし保護する
  if [ -f "$CODEX_CONFIG" ] && ! head -1 "$CODEX_CONFIG" | grep -q '^# AUTO-GENERATED by dotfiles/etc/sync-codex.sh'; then
    warn "refusing to overwrite hand-edited $CODEX_CONFIG (no AUTO-GENERATED header)"
    warn "remove the file or restore the header to enable sync"
    return 0
  fi

  local tmp
  tmp="$(mktemp "${CODEX_DIR}/config.toml.tmp.XXXXXX")"

  {
    echo "# AUTO-GENERATED by dotfiles/etc/sync-codex.sh from SSOT."
    echo "# Edit .codex/config.base.toml or the Claude-side SSOT files instead."
    echo
    cat "$CODEX_BASE_CONFIG"
    echo
    echo "# ---- AUTO-GENERATED MCP servers from mcp-servers.json ----"

    jq -r '.mcpServers | keys[]' "$MCP_SRC" | while IFS= read -r name; do
      local server type table_name command args env_json env_rendered url
      server="$(jq -c --arg name "$name" '.mcpServers[$name]' "$MCP_SRC")"

      if [ "$(printf '%s' "$server" | jq -r '.codexOnly // false')" = "false" ] &&
         { [ "$(printf '%s' "$server" | jq -r '.claudeCodeOnly // false')" = "true" ] ||
           [ "$(printf '%s' "$server" | jq -r '.openCodeOnly // false')" = "true" ]; }; then
        continue
      fi

      table_name="$(toml_quote "$name")"
      type="$(printf '%s' "$server" | jq -r '.type // (if .url then "remote" else "local" end)')"

      echo
      printf '[mcp_servers.%s]\n' "$table_name"
      echo "enabled = true"

      if [ "$type" = "remote" ]; then
        url="$(printf '%s' "$server" | jq -r '.url // empty')"
        if [ -z "$url" ]; then
          warn "remote MCP server '$name' has no url, skipping"
          continue
        fi
        printf 'url = %s\n' "$(toml_quote "$url")"
        if printf '%s' "$server" | jq -e '.bearer_token_env_var? // empty' >/dev/null; then
          printf 'bearer_token_env_var = %s\n' "$(toml_quote "$(printf '%s' "$server" | jq -r '.bearer_token_env_var')")"
        fi
      else
        command="$(printf '%s' "$server" | jq -r '.command // empty')"
        if [ -z "$command" ]; then
          warn "local MCP server '$name' has no command, skipping"
          continue
        fi
        args="$(printf '%s' "$server" | jq '.args // []' | toml_array)"
        printf 'command = %s\n' "$(toml_quote "$command")"
        printf 'args = %s\n' "$args"

        env_json="$(printf '%s' "$server" | jq -c '.env // {}')"
        if [ "$(printf '%s' "$env_json" | jq 'length')" != "0" ]; then
          # Note: rendered into an intermediate variable to avoid bash 3.2's
          # brace-expansion bug, where literal '{ ... , ... }' inside a single-
          # quoted filter nested in "$(...)" gets mis-expanded into two words.
          env_rendered="$(printf '%s' "$env_json" | jq -r 'to_entries | map("\(.key) = \(.value | @json)") | "{ " + join(", ") + " }"')"
          printf 'env = %s\n' "$env_rendered"
        fi
      fi
    done
  } > "$tmp"

  mv -f "$tmp" "$CODEX_CONFIG"
  log "wrote $CODEX_CONFIG"
}

copy_with_header() {
  local src="$1" dst="$2" label="$3"
  [ -f "$src" ] || return 0
  {
    printf '<!-- AUTO-GENERATED by etc/sync-codex.sh from %s. Do not edit. -->\n\n' "$label"
    cat "$src"
  } > "$dst"
  log "wrote $dst"
}

quote_yaml_scalar() {
  local raw="$1"
  local decoded="$raw"

  case "$raw" in
    \"*\")
      decoded="$(printf '%s' "$raw" | jq -r . 2>/dev/null || printf '%s' "$raw")"
      ;;
  esac

  printf '%s' "$decoded" | jq -Rs .
}

normalize_codex_skill_frontmatter() {
  local file="$1"
  [ -f "$file" ] || return 0

  local tmp
  tmp="$(mktemp "${file}.tmp.XXXXXX")"

  local fence_count=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "---" ]; then
      fence_count=$((fence_count + 1))
      printf '%s\n' "$line" >> "$tmp"
      continue
    fi

    if [ "$fence_count" -eq 1 ] && [[ "$line" =~ ^([A-Za-z0-9_-]+):[[:space:]]*(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      printf '%s: %s\n' "$key" "$(quote_yaml_scalar "$value")" >> "$tmp"
    else
      printf '%s\n' "$line" >> "$tmp"
    fi
  done < "$file"

  mv -f "$tmp" "$file"
}

sync_agents() {
  local src_dir="${CLAUDE_DIR}/agents"
  [ -d "$src_dir" ] || return 0

  for f in "$src_dir"/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "${CODEX_AGENTS_DIR}/$(basename "$f")" ".claude/agents/$(basename "$f")"
  done

  for f in "$CODEX_AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    if ! head -1 "$f" | grep -q '^<!-- AUTO-GENERATED by etc/sync-codex.sh'; then
      continue
    fi
    if [ ! -f "${src_dir}/$(basename "$f")" ]; then
      rm -f "$f"
      log "removed orphan agent: $(basename "$f")"
    fi
  done
}

sync_skills() {
  local src_dir="${CLAUDE_DIR}/skills"
  [ -d "$src_dir" ] || return 0

  for d in "$src_dir"/*; do
    [ -d "$d" ] || continue
    local name dst marker
    name="$(basename "$d")"
    dst="${CODEX_SKILLS_DIR}/${name}"
    marker="${dst}/.codex-generated-from-claude"

    if [ -e "$dst" ] && [ ! -f "$marker" ]; then
      warn "not overwriting non-generated skill: $dst"
      continue
    fi

    rm -rf "$dst"
    mkdir -p "$dst"
    cp -a "$d"/. "$dst"/
    rm -rf "$dst/.git"
    normalize_codex_skill_frontmatter "$dst/SKILL.md"
    touch "$marker"
    log "mirrored skill: $name"
  done

  for d in "$CODEX_SKILLS_DIR"/*; do
    [ -d "$d" ] || continue
    [ -f "$d/.codex-generated-from-claude" ] || continue
    if [ ! -d "${src_dir}/$(basename "$d")" ]; then
      rm -rf "$d"
      log "removed orphan skill: $(basename "$d")"
    fi
  done
}

write_codex_config
copy_with_header "${CLAUDE_DIR}/CLAUDE.md" "${CODEX_DIR}/AGENTS.md" ".claude/CLAUDE.md"
copy_with_header "${CLAUDE_DIR}/format.md" "${CODEX_DIR}/format.md" ".claude/format.md"
copy_with_header "${CLAUDE_DIR}/pir-handoff.md" "${CODEX_DIR}/pir-handoff.md" ".claude/pir-handoff.md"
sync_agents
sync_skills

log "done"
