#!/usr/bin/env bash
# Antigravity (Gemini) sync / config 契約テスト。
#
#   bash etc/test-antigravity-contracts.sh
#
# ライブドットファイルの生成物を --check で検証し、ルールサマリー、MCPフィルタ、
# hooks/auto-gateの構文、skills symlinkを確認する。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail=0
pass=0

ok() { echo "PASS: $*"; pass=$((pass + 1)); }
bad() { echo "FAIL: $*" >&2; fail=$((fail + 1)); }

# --- A. sync --check / idempotent ---
if bash "${SCRIPT_DIR}/sync-antigravity.sh" --check >/dev/null; then
  ok "sync-antigravity --check"
else
  bad "sync-antigravity --check"
fi

RULE="${DOT_DIR}/.gemini/config/rules/shared-agents.md"
MCP="${DOT_DIR}/.gemini/config/mcp_config.json"
HOOKS="${DOT_DIR}/.gemini/config/hooks.json"
SCRIPT="${DOT_DIR}/.gemini/config/scripts/auto-gate.py"
SKILLS="${DOT_DIR}/.gemini/config/skills"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"

# --- B. rules = summary, not full copy ---
if [ -f "$RULE" ] \
  && grep -q 'AUTO-GENERATED by dotfiles/etc/sync-antigravity.sh' "$RULE" \
  && grep -q 'Do \*\*not\*\* treat this rule as a full copy' "$RULE" \
  && [ "$(wc -c <"$RULE")" -lt "$(wc -c <"$AGENTS_SRC")" ]; then
  ok "rules summary-not-full-copy"
else
  bad "rules summary-not-full-copy"
fi

# --- C. MCP filter ---
if command -v jq >/dev/null 2>&1; then
  if jq -e '._generated_by == "dotfiles/etc/sync-antigravity.sh"' "$MCP" >/dev/null; then
    ok "mcp _generated_by marker"
  else
    bad "mcp _generated_by marker"
  fi

  leaked="$(
    jq -r --argjson out "$(jq '.mcpServers // {}' "$MCP")" '
      .mcpServers
      | to_entries[]
      | select(.value.claudeCodeOnly == true or .value.openCodeOnly == true or .value.codexOnly == true or .value.cursorOnly == true)
      | .key as $k
      | select($out[$k] != null)
      | $k
    ' "${DOT_DIR}/mcp-servers.json"
  )"
  if [ -z "$leaked" ]; then
    ok "mcp other-runtime-only excluded"
  else
    bad "mcp leaked servers: $leaked"
  fi
else
  ok "mcp checks skipped (no jq)"
fi

# --- D. hooks and auto-gate script ---
if [ -f "$HOOKS" ]; then
  ok "hooks.json exists"
else
  bad "hooks.json missing"
fi

if [ -f "$SCRIPT" ] && [ -x "$SCRIPT" ]; then
  ok "auto-gate.py executable"
else
  bad "auto-gate.py missing or not executable"
fi

if command -v python3 >/dev/null 2>&1; then
  if python3 -c 'import sys; compile(sys.stdin.read(), sys.argv[1], "exec")' "$SCRIPT" < "$SCRIPT" 2>/dev/null; then
    ok "auto-gate.py syntax valid"
  else
    bad "auto-gate.py syntax error"
  fi
fi

# --- E. skills symlink ---
if [ -d "$SKILLS" ] && [ "$(cd -P "$SKILLS" && pwd)" = "$(cd -P "${DOT_DIR}/.agents/skills" && pwd)" ]; then
  ok "skills linked/available"
else
  bad "skills missing"
fi

echo "Antigravity contracts: pass=${pass} fail=${fail}"
[ "$fail" -eq 0 ]
