#!/usr/bin/env bash
# Validate the Codex configuration adapter without touching the repository's
# generated files or the user's real $HOME state.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail() {
  echo "[test-codex-config] FAIL: $*" >&2
  exit 1
}

expect_line() {
  local file="$1" line="$2"
  grep -Fqx "$line" "$file" || fail "missing line in $file: $line"
}

expect_no_line() {
  local file="$1" line="$2"
  if grep -Fqx "$line" "$file"; then
    fail "unexpected line in $file: $line"
  fi
}

expect_count() {
  local file="$1" needle="$2" expected="$3" actual
  actual="$(grep -F -c "$needle" "$file" || true)"
  [ "$actual" -eq "$expected" ] ||
    fail "$file: expected $expected occurrences of '$needle', got $actual"
}

command -v jq >/dev/null 2>&1 || fail "jq is required"
command -v python3 >/dev/null 2>&1 || fail "python3 is required"
command -v uv >/dev/null 2>&1 || fail "uv is required for TOML validation"
ORIGINAL_PATH="$PATH"

TEST_ROOT="$(mktemp -d "${TMPDIR:-/private/tmp}/test-codex-config.XXXXXX")"
trap 'rm -rf "$TEST_ROOT"' EXIT
FIXTURE="$TEST_ROOT/fixture with [meta];\$path"
HOME_FIXTURE="$FIXTURE/home"

mkdir -p \
  "$FIXTURE/etc" \
  "$FIXTURE/.codex/skills/native-both" \
  "$FIXTURE/.codex/skills/native-duplicate" \
  "$FIXTURE/.codex/skills/native-home" \
  "$FIXTURE/.codex/skills/native-no-shared" \
  "$FIXTURE/.codex/skills/native-user-owned" \
  "$FIXTURE/.codex/skills/foo" \
  "$FIXTURE/.agents/skills/native-both" \
  "$FIXTURE/.agents/skills/native-duplicate" \
  "$FIXTURE/.agents/skills/native-user-owned" \
  "$FIXTURE/.agents/skills/foo-bar" \
  "$FIXTURE/.agents/skills/shared-only" \
  "$HOME_FIXTURE/.agents/skills/native-both" \
  "$HOME_FIXTURE/.agents/skills/native-home" \
  "$HOME_FIXTURE/.codex"

cp "$DOT_DIR/etc/sync-codex.sh" "$FIXTURE/etc/sync-codex.sh"
cp "$DOT_DIR/.codex/config.base.toml" "$FIXTURE/.codex/config.base.toml"
mkdir -p "$FIXTURE/.codex/skills/pir2/references"
cp "$DOT_DIR/.codex/skills/pir2/references/handoff-protocol.md" "$FIXTURE/.codex/skills/pir2/references/handoff-protocol.md"
cp "$DOT_DIR/.codex/skills/pir2/references/protocol.md" "$FIXTURE/.codex/skills/pir2/references/protocol.md"
chmod +x "$FIXTURE/etc/sync-codex.sh"

if grep -Eq '[|][[:space:]]*atomic_publish' "$FIXTURE/etc/sync-codex.sh"; then
  fail "Codex producers must finish before atomic publication"
fi

printf '%s\n' '{"mcpServers":{}}' > "$FIXTURE/mcp-servers.json"
printf '%s\n' '# fixture shared instructions' > "$FIXTURE/AGENTS.md"
printf '%s\n' '# fixture Codex supplement' > "$FIXTURE/.codex/codex-native-supplement.md"
printf '%s\n' '# docs ~/.agents/skills/native-duplicate/ref ${HOME}/.agents/skills/native-home/ref ~/.agents/skills/foo/ref ~/.agents/skills/foo-bar/ref ~/.claude/skills/shared-only/ref ~/.agents/skills/shared-only/references/fable-model.md' > "$FIXTURE/.claude-format.md"
printf '%s\n' '# protocol claude-sonnet-4-6 haiku sonnet opus fable claude-fable-5-1 全て `claude-sonnet-4-6` モデル。' > "$FIXTURE/.claude-protocol.md"
mkdir -p "$FIXTURE/.claude"
mv "$FIXTURE/.claude-format.md" "$FIXTURE/.claude/format.md"
mv "$FIXTURE/.claude-protocol.md" "$FIXTURE/.claude/pir2-protocol.md"
printf '%s\n' '# Codex-native agent delegation document' > "$FIXTURE/.codex/agent-delegation.md"

for skill in native-both native-duplicate native-home native-no-shared native-user-owned foo; do
  printf '# native %s\n' "$skill" > "$FIXTURE/.codex/skills/$skill/SKILL.md"
done
printf '%s\n' '# shared native-both (repository)' > "$FIXTURE/.agents/skills/native-both/SKILL.md"
printf '%s\n' '# shared native-both (home)' > "$HOME_FIXTURE/.agents/skills/native-both/SKILL.md"
printf '%s\n' '# shared native-duplicate' > "$FIXTURE/.agents/skills/native-duplicate/SKILL.md"
printf '%s\n' '# shared native-home' > "$HOME_FIXTURE/.agents/skills/native-home/SKILL.md"
printf '%s\n' '# shared native-user-owned' > "$FIXTURE/.agents/skills/native-user-owned/SKILL.md"
printf '%s\n' '# shared prefix-only skill' > "$FIXTURE/.agents/skills/foo-bar/SKILL.md"
printf '%s\n' '# shared only' > "$FIXTURE/.agents/skills/shared-only/SKILL.md"
ln -s "$FIXTURE/.agents/skills/native-duplicate" "$HOME_FIXTURE/.agents/skills/native-duplicate"

USER_OWNED_SKILL="$FIXTURE/.agents/skills/native-user-owned/SKILL.md"
cat > "$FIXTURE/.codex/config.toml" <<CONFIG
# AUTO-GENERATED by dotfiles/etc/sync-codex.sh from SSOT.
sandbox_mode = "workspace-write"

[[skills.config]]
path = "$USER_OWNED_SKILL"
enabled = false

[[skills.config]]
path = "/unrelated/user-skill/SKILL.md"
enabled = true

# ---- AUTO-GENERATED shared skill suppression (native Codex wins) ----
[[skills.config]]
path = "/stale/generated/SKILL.md"
enabled = false

[projects."$FIXTURE"]
trust_level = "trusted"

[[hooks.PostToolUse]]
matcher = "Edit|Write|MultiEdit"

[[hooks.PostToolUse.hooks]]
type = "command"
command = "bash stale-hook"

[hooks.state]

[hooks.state."$HOME_FIXTURE/.codex/config.toml:post_tool_use:0:0"]
enabled = true
trusted_hash = "sha256:keep-home"

[hooks.state."$FIXTURE/.codex/config.toml:post_tool_use:0:0"]
trusted_hash = "sha256:keep-repo"
CONFIG

printf '%s\n' 'ui-state-sentinel' > "$HOME_FIXTURE/.codex/.codex-global-state.json"

run_sync() {
  local uv_cache="$TEST_ROOT/uv-cache"
  mkdir -p "$uv_cache"
  (
    cd "$FIXTURE"
    HOME="$HOME_FIXTURE" UV_CACHE_DIR="$uv_cache" bash etc/sync-codex.sh >/dev/null
  )
}

run_sync
cp "$FIXTURE/.codex/config.toml" "$TEST_ROOT/config.first.toml"
cp "$FIXTURE/.codex/format.md" "$TEST_ROOT/format.first.md"
cp "$FIXTURE/.codex/pir2-protocol.md" "$TEST_ROOT/protocol.first.md"
cp "$FIXTURE/.codex/agent-delegation.md" "$TEST_ROOT/agent-delegation.first.md"
ui_hash_before="$(shasum "$HOME_FIXTURE/.codex/.codex-global-state.json" | awk '{print $1}')"

CONFIG="$FIXTURE/.codex/config.toml"
printf '%s\n' '[[skills.config]]' "path = \"$FIXTURE/.agents/skills/user-after-end/SKILL.md\"" 'enabled = true' >> "$CONFIG"
run_sync
cp "$CONFIG" "$TEST_ROOT/config.second.toml"
cmp -s "$TEST_ROOT/format.first.md" "$FIXTURE/.codex/format.md" || fail "format sync is not idempotent"
cmp -s "$TEST_ROOT/protocol.first.md" "$FIXTURE/.codex/pir2-protocol.md" || fail "protocol sync is not idempotent"
cmp -s "$TEST_ROOT/agent-delegation.first.md" "$FIXTURE/.codex/agent-delegation.md" || fail "native agent-delegation document was overwritten"
ui_hash_after="$(shasum "$HOME_FIXTURE/.codex/.codex-global-state.json" | awk '{print $1}')"
[ "$ui_hash_before" = "$ui_hash_after" ] || fail "UI state changed"

run_sync
cmp -s "$TEST_ROOT/config.second.toml" "$CONFIG" || fail "config sync is not idempotent after preserving a user table"

# A generated config may be reached through a user-created symlink (for
# example, a runtime link into a shared config directory).  Publication must
# replace the generated target atomically while keeping that route intact.
SYMLINK_TARGET="$FIXTURE/.codex/config-target.toml"
cp "$CONFIG" "$SYMLINK_TARGET"
rm -f "$CONFIG"
ln -s "$(basename "$SYMLINK_TARGET")" "$CONFIG"
run_sync
[ -L "$CONFIG" ] || fail "config symlink was replaced during publication"
cmp -s "$TEST_ROOT/config.second.toml" "$SYMLINK_TARGET" || fail "generated symlink target was not updated atomically"

expected_hook_path="$(cd "$FIXTURE/etc" && pwd)/sync-codex.sh"
expected_hook_command="$(printf '%s' "bash $(printf '%q' "$expected_hook_path")" | jq -Rs .)"
expect_line "$SYMLINK_TARGET" "command = ${expected_hook_command}"

# A producer that emits partial output and then fails must not publish that
# partial output.  The failing sed is injected only in this private fixture;
# the real sync script remains the producer under test.
producer_fail_bin="$TEST_ROOT/producer-fail-bin"
producer_fail_log="$TEST_ROOT/producer-fail.log"
mkdir -p "$producer_fail_bin"
printf '%s\n' '#!/bin/sh' 'printf "%s\\n" "PARTIAL_PRODUCER"' 'exit 23' > "$producer_fail_bin/sed"
chmod +x "$producer_fail_bin/sed"
producer_target="$FIXTURE/.codex/format.md"
producer_before="$(shasum "$producer_target" | awk '{print $1}')"
if (
  cd "$FIXTURE"
  HOME="$HOME_FIXTURE" UV_CACHE_DIR="$TEST_ROOT/uv-cache" \
    PATH="$producer_fail_bin:$ORIGINAL_PATH" bash etc/sync-codex.sh
) >"$producer_fail_log" 2>&1; then
  fail "failed Codex producer returns failure"
else
  :
fi
producer_after="$(shasum "$producer_target" | awk '{print $1}')"
[ "$producer_before" = "$producer_after" ] || fail "failed Codex producer changed target"
if grep -q 'PARTIAL_PRODUCER' "$producer_target"; then
  fail "failed Codex producer published partial output"
fi

agent_producer_fail_bin="$TEST_ROOT/agent-producer-fail-bin"
agent_producer_fail_log="$TEST_ROOT/agent-producer-fail.log"
real_cat="$(command -v cat)"
mkdir -p "$agent_producer_fail_bin"
printf '%s\n' \
  '#!/bin/sh' \
  'if [ "${1##*/}" = "AGENTS.md" ]; then' \
  '  printf "%s\\n" "PARTIAL_AGENT_PRODUCER"' \
  '  exit 23' \
  'fi' \
  'exec "${REAL_CAT:?}" "$@"' >"$agent_producer_fail_bin/cat"
chmod +x "$agent_producer_fail_bin/cat"
agent_producer_target="$FIXTURE/.codex/AGENTS.md"
agent_producer_before="$(shasum "$agent_producer_target" | awk '{print $1}')"
if (
  cd "$FIXTURE"
  REAL_CAT="$real_cat" \
    HOME="$HOME_FIXTURE" UV_CACHE_DIR="$TEST_ROOT/uv-cache" \
    PATH="$agent_producer_fail_bin:$ORIGINAL_PATH" bash etc/sync-codex.sh
) >"$agent_producer_fail_log" 2>&1; then
  fail "failed Codex AGENTS producer returns failure"
fi
agent_producer_after="$(shasum "$agent_producer_target" | awk '{print $1}')"
[ "$agent_producer_before" = "$agent_producer_after" ] || fail "failed Codex AGENTS producer changed target"
if grep -q 'PARTIAL_AGENT_PRODUCER' "$agent_producer_target"; then
  fail "failed Codex AGENTS producer published partial output"
fi

rm -f "$CONFIG"
mkdir "$CONFIG"
if run_sync >/dev/null 2>&1; then
  fail "Codex rejects generated directory target"
fi
if [ -z "$(find "$CONFIG" -mindepth 1 -print -quit 2>/dev/null)" ]; then
  :
else
  fail "Codex leaves generated directory target empty"
fi
rmdir "$CONFIG"
cp "$TEST_ROOT/config.second.toml" "$CONFIG"

python3 - "$FIXTURE/.codex/config.toml" "$FIXTURE" "$HOME_FIXTURE" <<'PY'
import sys
import tomllib
from pathlib import Path

config_path, fixture_path, home_path = sys.argv[1:]
fixture = Path(fixture_path)
home = Path(home_path)
with open(config_path, "rb") as fh:
    config = tomllib.load(fh)

assert config["model"] == "gpt-6-astra"
assert config["model_reasoning_effort"] == "high"
agents = config["agents"]
assert agents["enabled"] is True
assert agents["default_subagent_model"] == "gpt-5.6-luna"
assert agents["default_subagent_reasoning_effort"] == "max"
assert agents["max_concurrent_threads_per_session"] == 6
assert "max_threads" not in agents
assert agents["max_depth"] == 2
assert agents["job_max_runtime_seconds"] == 1800

features = config["features"]
assert features["hooks"] is True
assert features["prevent_idle_sleep"] is True
assert features["context_management"]["experimental_mode"] is True
assert isinstance(features["context_management"], dict)

skills = config["skills"]["config"]
paths = [entry["path"] for entry in skills]
assert len(paths) == len(set(paths)), paths
assert paths.count(fixture_path + "/.agents/skills/native-user-owned/SKILL.md") == 1
assert paths.count("/unrelated/user-skill/SKILL.md") == 1
assert paths.count(fixture_path + "/.agents/skills/user-after-end/SKILL.md") == 1
assert paths.count(str((fixture / ".agents/skills/native-duplicate/SKILL.md").resolve())) == 1
assert paths.count(str((home / ".agents/skills/native-home/SKILL.md").resolve())) == 1
assert paths.count(str((fixture / ".agents/skills/native-both/SKILL.md").resolve())) == 1
assert paths.count(str((home / ".agents/skills/native-both/SKILL.md").resolve())) == 1
assert str((fixture / ".agents/skills/shared-only/SKILL.md").resolve()) not in paths
assert str((fixture / ".agents/skills/foo-bar/SKILL.md").resolve()) not in paths
assert str((fixture / ".agents/skills/native-no-shared/SKILL.md").resolve()) not in paths
for entry in skills:
    if entry["path"] not in {
        "/unrelated/user-skill/SKILL.md",
        fixture_path + "/.agents/skills/user-after-end/SKILL.md",
    }:
        assert entry["enabled"] is False

projects = config["projects"]
assert projects[fixture_path]["trust_level"] == "trusted"

state = config["hooks"]["state"]
assert set(state) == {
    f"{home_path}/.codex/config.toml:post_tool_use:0:0",
    f"{fixture_path}/.codex/config.toml:post_tool_use:0:0",
}
assert state[f"{home_path}/.codex/config.toml:post_tool_use:0:0"]["trusted_hash"] == "sha256:keep-home"
assert state[f"{fixture_path}/.codex/config.toml:post_tool_use:0:0"]["trusted_hash"] == "sha256:keep-repo"
assert len(config["hooks"]["PostToolUse"]) == 1
assert config["hooks"]["PostToolUse"][0]["matcher"] == "Edit|Write|MultiEdit"
PY

CONFIG="$FIXTURE/.codex/config.toml"
PROTOCOL="$FIXTURE/.codex/pir2-protocol.md"
expect_line "$FIXTURE/.codex/pir-handoff.md" '# Codex PIR² handoff'
if grep -q 'run-dir-base.md\|Bash rm' "$FIXTURE/.codex/pir-handoff.md"; then
  fail "handoff adapter reintroduced a missing reference or destructive cleanup"
fi
FORMAT="$FIXTURE/.codex/format.md"
expect_count "$CONFIG" "[features]" 1
expect_count "$CONFIG" "[features.context_management]" 1
expect_count "$CONFIG" "# ---- AUTO-GENERATED shared skill suppression" 1
expect_count "$CONFIG" "# ---- END AUTO-GENERATED shared skill suppression" 1
expect_count "$CONFIG" "# ---- preserved per-machine skills configuration" 1
expect_count "$CONFIG" "[[skills.config]]" 7
expect_count "$CONFIG" "trusted_hash =" 2
expect_no_line "$CONFIG" "context_management = true"
expect_no_line "$CONFIG" "path = \"/stale/generated/SKILL.md\""
expect_line "$CONFIG" "path = \"$FIXTURE/.agents/skills/user-after-end/SKILL.md\""

expect_line "$FORMAT" '# docs ~/.codex/skills/native-duplicate/ref ${HOME}/.codex/skills/native-home/ref ~/.codex/skills/foo/ref ~/.agents/skills/foo-bar/ref ~/.agents/skills/shared-only/ref ~/.agents/skills/shared-only/references/fable-model.md'
expect_line "$PROTOCOL" '# Codex PIR² 内部プロトコル'
tail -n +3 "$PROTOCOL" > "$TEST_ROOT/protocol-body.md"
cmp -s "$TEST_ROOT/protocol-body.md" "$FIXTURE/.codex/skills/pir2/references/protocol.md" || fail "protocol adapter did not preserve native source"

# A symlink to a non-generated file is user-owned and must remain untouched.
PROTECTED_TARGET="$FIXTURE/.codex/protected-config.toml"
printf '%s\n' 'protected config' > "$PROTECTED_TARGET"
rm -f "$CONFIG"
ln -s "$(basename "$PROTECTED_TARGET")" "$CONFIG"
run_sync
[ -L "$CONFIG" ] || fail "protected config symlink was replaced"
assert_line="$(cat "$PROTECTED_TARGET")"
[ "$assert_line" = 'protected config' ] || fail "protected symlink target was overwritten"

echo "[test-codex-config] PASS"
