#!/usr/bin/env bash
# OpenCode sync 契約テスト。
#
#   bash etc/test-opencode-contracts.sh
#
# ライブ dotfiles の生成物を sync-opencode.sh --check で検証し、fake HOME での
# fresh sync・冪等性・agent frontmatter 変換・AGENTS.md 補足セクション・孤児削除を
# mktemp フィクスチャで確認する。本番 HOME への破壊的書き込みはしない。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/opencode-contracts.XXXXXX")"
trap 'find "$WORK" -mindepth 1 -delete 2>/dev/null; rmdir "$WORK" 2>/dev/null || true' EXIT

fail=0
pass=0

ok() { echo "PASS: $*"; pass=$((pass + 1)); }
bad() { echo "FAIL: $*" >&2; fail=$((fail + 1)); }

assert_true() {
  local name="$1"
  shift
  if "$@"; then
    ok "$name"
  else
    bad "$name"
  fi
}

TARGET_JSON="${HOME}/.config/opencode/opencode.json"
TARGET_AGENTS_MD="${HOME}/.config/opencode/AGENTS.md"
TARGET_AGENTS_DIR="${HOME}/.config/opencode/agents"

# frontmatter 本文抽出（sync-opencode.sh の extract_body と同一ロジック）
body_of() {
  awk 'BEGIN { c = 0 } /^---[[:space:]]*$/ { c++; next } c >= 2 { print }' "$1"
}

scalar_key() {
  local file="$1" key="$2"
  awk -v k="$key" '
    BEGIN { f = 0 }
    f == 0 && $0 ~ ("^" k ":[ \t]") { sub("^" k ":[ \t]+", ""); print; f = 1; exit }
  ' "$file"
}

expected_model() {
  local m="${1:-}"
  [ -z "$m" ] && return 0
  case "$m" in
    */*) printf '%s' "$m" ;;
    sonnet) printf '%s' 'anthropic/claude-sonnet-5' ;;
    opus) printf '%s' 'anthropic/claude-opus-4-8' ;;
    fable) printf '%s' 'anthropic/claude-fable-5' ;;
    claude-*) printf 'anthropic/%s' "$m" ;;
    *) printf '%s' "$m" ;;
  esac
}

# --- A. live sync --check ---
if bash "${SCRIPT_DIR}/sync-opencode.sh" --check >/dev/null; then
  ok "sync-opencode --check (live)"
else
  bad "sync-opencode --check (live)"
fi

# --- B. fake HOME fresh sync + idempotency ---
fake_home="${WORK}/home"
if HOME="$fake_home" bash "${SCRIPT_DIR}/sync-opencode.sh" >/dev/null; then
  ok "fresh sync with fake HOME"
else
  bad "fresh sync with fake HOME"
fi

if HOME="$fake_home" bash "${SCRIPT_DIR}/sync-opencode.sh" --check >/dev/null; then
  ok "re-run is idempotent (--check passes on fresh output)"
else
  bad "re-run is idempotent (--check passes on fresh output)"
fi

# --- C. opencode.json contract (generated file carries JSONC header comments) ---
if command -v jq >/dev/null 2>&1 && [ -f "$TARGET_JSON" ]; then
  strip_jsonc() { grep -v '^[[:space:]]*//' "$1"; }

  if strip_jsonc "$TARGET_JSON" | jq -e '."$schema" == "https://opencode.ai/config.json"' >/dev/null; then
    ok "opencode.json has \$schema"
  else
    bad "opencode.json has \$schema"
  fi

  leaked="$(jq -r --argjson out "$(strip_jsonc "$TARGET_JSON" | jq '.mcp // {}')" '
    .mcpServers
    | to_entries[]
    | select(.value.claudeCodeOnly == true or .value.codexOnly == true)
    | .key as $k
    | select($out[$k] != null)
    | $k
  ' "${DOT_DIR}/mcp-servers.json")"
  if [ -z "$leaked" ]; then
    ok "mcp excludes claudeCodeOnly/codexOnly servers"
  else
    bad "mcp leaked claudeCodeOnly/codexOnly servers: $leaked"
  fi

  if strip_jsonc "$TARGET_JSON" | jq -e '.lsp == true' >/dev/null; then
    ok "lsp explicitly enabled (OpenCode defaults to disabled)"
  else
    bad "lsp explicitly enabled (OpenCode defaults to disabled)"
  fi

  if strip_jsonc "$TARGET_JSON" | jq -e '.permission.bash["*"] == "allow"' >/dev/null; then
    ok "permission bash defaults to allow (approval-fatigue policy)"
  else
    bad "permission bash defaults to allow (approval-fatigue policy)"
  fi

  if strip_jsonc "$TARGET_JSON" | jq -e '.permission.bash["rm -rf *"] == "ask" and .permission.bash["sudo *"] == "ask" and .permission.bash["git push *"] == "ask" and .permission.edit == "allow"' >/dev/null; then
    ok "dangerous bash ops ask + edit allow"
  else
    bad "dangerous bash ops ask + edit allow"
  fi
else
  bad "jq + opencode.json required for MCP assertions"
fi

# --- D. agent conversion contract ---
missing_agents=""
bad_mode=""
bad_model=""
bad_header=""
bad_body=""
for src in "${DOT_DIR}/.claude/agents"/*.md; do
  [ -f "$src" ] || continue
  base="$(basename "$src")"
  dst="${TARGET_AGENTS_DIR}/${base}"
  if [ ! -f "$dst" ]; then
    missing_agents="${missing_agents} ${base}"
    continue
  fi
  head -1 "$dst" | grep -q '^<!-- AUTO-GENERATED by etc/sync-opencode.sh' || bad_header="${bad_header} ${base}"
  grep -q '^mode: subagent$' "$dst" || bad_mode="${bad_mode} ${base}"

  want_model="$(expected_model "$(scalar_key "$src" "model")")"
  got_model="$(scalar_key "$dst" "model")"
  if [ "$got_model" != "$want_model" ]; then
    bad_model="${bad_model} ${base}:${got_model:-<empty>}!=${want_model:-<none>}"
  fi

  if ! cmp -s <(body_of "$src") <(tail -n +2 "$dst" | body_of /dev/stdin); then
    bad_body="${bad_body} ${base}"
  fi
done
if [ -z "$missing_agents" ]; then
  ok "all SSOT agents converted"
else
  bad "agents missing from generated dir:${missing_agents}"
fi
[ -z "$bad_header" ] && ok "agents have AUTO-GENERATED header" || bad "agents missing header:${bad_header}"
[ -z "$bad_mode" ] && ok "agents declare mode: subagent" || bad "agents missing mode:${bad_mode}"
[ -z "$bad_model" ] && ok "agent models mapped to anthropic/<id>" || bad "agent model mapping broken:${bad_model}"
[ -z "$bad_body" ] && ok "agent bodies copied verbatim" || bad "agent bodies diverged:${bad_body}"

# --- E. generated AGENTS.md contract ---
if [ -f "$TARGET_AGENTS_MD" ]; then
  head -1 "$TARGET_AGENTS_MD" | grep -q '<!-- AUTO-GENERATED by dotfiles/etc/sync-opencode.sh' \
    && ok "generated AGENTS.md has header" || bad "generated AGENTS.md has header"

  # 生成物は 5 行ヘッダーの直後に SSOT 全文を埋め込む。byte-count ベースで prefix 一致を検証
  ssot_bytes="$(wc -c < "$DOT_DIR/AGENTS.md")"
  tail -n +6 "$TARGET_AGENTS_MD" | head -c "$ssot_bytes" > "${WORK}/ssot-embed.tmp"
  if cmp -s "${WORK}/ssot-embed.tmp" "$DOT_DIR/AGENTS.md"; then
    ok "generated AGENTS.md embeds shared AGENTS.md verbatim"
  else
    bad "generated AGENTS.md embeds shared AGENTS.md verbatim"
  fi

  for section in "サブエージェント起動の読み替え" "スキルの発見経路" "動作対象外スキル" "動作可能スキル" "互換性ギャップの諦め"; do
    assert_true "supplement section present: $section" grep -q "^## $section" "$TARGET_AGENTS_MD"
  done

  stale=""
  grep -q "skill-creator" "$TARGET_AGENTS_MD" && stale="${stale} skill-creator"
  grep -q "claude-sonnet-4-6" "$TARGET_AGENTS_MD" && stale="${stale} claude-sonnet-4-6"
  if [ -z "$stale" ]; then
    ok "no stale references (skill-creator / old model ids)"
  else
    bad "stale references in generated AGENTS.md:${stale}"
  fi
else
  bad "generated AGENTS.md exists"
fi

# --- F. orphan cleanup + hand-written protection on fake HOME ---
orphan="${fake_home}/.config/opencode/agents/orphan-agent.md"
handwritten="${fake_home}/.config/opencode/agents/hand-written-agent.md"
{
  printf '<!-- AUTO-GENERATED by etc/sync-opencode.sh from gone.md. Do not edit. -->\n'
  printf -- '---\ndescription: orphan\nmode: subagent\n---\norphan body\n'
} > "$orphan"
printf '# HAND WRITTEN\n' > "$handwritten"

HOME="$fake_home" bash "${SCRIPT_DIR}/sync-opencode.sh" >/dev/null

[ ! -f "$orphan" ] && ok "orphan AUTO-GENERATED agent removed" || bad "orphan AUTO-GENERATED agent removed"
[ -f "$handwritten" ] && ok "hand-written agent survives cleanup" || bad "hand-written agent survives cleanup"

echo
echo "opencode contracts: ${pass} passed, ${fail} failed"
if [ "$fail" -ne 0 ]; then
  exit 1
fi
exit 0
