#!/usr/bin/env python3
"""Exercise the hook command emitted by the real Codex config generator.

Run: uv run --python 3.13 python etc/test-codex-native-sync-hook.py
All generated settings, symlinks and producer invocations stay in a temporary
HOME/repository. No Codex inference, real home edits or network calls occur.
"""

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest


REPO = Path(__file__).resolve().parent.parent


class NativeHookTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp = tempfile.TemporaryDirectory(prefix="codex-native-hook-")
        cls.addClassCleanup(cls.temp.cleanup)
        cls.base = Path(cls.temp.name)
        cls.root = cls.base / "dotfiles with $spaces'"
        cls.etc = cls.root / "etc"
        cls.etc.mkdir(parents=True)
        cls.home = cls.base / "home"
        cls.home.mkdir()
        cls.other = cls.base / "application"
        cls.other.mkdir()
        for name in ("sync-codex.sh", "sync-codex-hook.py"):
            shutil.copyfile(REPO / "etc" / name, cls.etc / name)
        codex = cls.root / ".codex"
        codex.mkdir()
        (cls.root / "AGENTS.md").write_text("# Fixture\n", encoding="utf-8")
        (cls.root / "mcp-servers.json").write_text('{"mcpServers": {}}\n', encoding="utf-8")
        (codex / "codex-native-supplement.md").write_text("# Native fixture\n", encoding="utf-8")
        (codex / "config.base.toml").write_text('[features]\nhooks = true\n', encoding="utf-8")
        cls.trust = '[hooks.state.fixture]\ntrusted_hash = "existing-state-do-not-change"\n'
        (codex / "config.toml").write_text(
            '# AUTO-GENERATED by dotfiles/etc/sync-codex.sh from SSOT.\n' + cls.trust,
            encoding="utf-8")
        cls.env = dict(os.environ, HOME=str(cls.home), UV_OFFLINE="1",
                       UV_PYTHON_DOWNLOADS="never", UV_CACHE_DIR=str(cls.base / "uv-cache"))
        result = subprocess.run(["bash", str(cls.etc / "sync-codex.sh")],
                                env=cls.env, capture_output=True, text=True, timeout=40)
        if result.returncode:
            raise RuntimeError("Fixture generation failed: " + result.stderr)
        cls.generated = (codex / "config.toml").read_text(encoding="utf-8")
        cls.config = tomllib.loads(cls.generated)
        cls.command = cls.config["hooks"]["PostToolUse"][0]["hooks"][0]["command"]
        cls.calls = cls.base / "producer-calls"
        cls.env["CALLS_PATH"] = str(cls.calls)
        # Replace only the fixture producer AFTER obtaining its generated
        # hook command. This catches a generator still invoking sync directly.
        (cls.etc / "sync-codex.sh").write_text(
            '#!/usr/bin/env bash\nprintf "call\\n" >> "$CALLS_PATH"\n'
            'echo private-producer-output >&2\nexit "${PRODUCER_EXIT:-0}"\n',
            encoding="utf-8")

    def setUp(self):
        self.calls.write_text("", encoding="utf-8")

    def event(self, body, cwd=None):
        return {"hook_event_name": "PostToolUse", "tool_name": "apply_patch",
                "cwd": str(cwd or self.root),
                "tool_input": {"command": "*** Begin Patch\n" + body + "\n*** End Patch"}}

    def invoke(self, event, expected=0, failure=False, raw=False):
        result = subprocess.run(["bash", "-c", self.command], cwd=str(self.other),
                                input=event if raw else json.dumps(event),
                                env=dict(self.env, PRODUCER_EXIT="23" if failure else "0"),
                                capture_output=True, text=True, timeout=10)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.calls.read_text().count("call\n"), expected)
        self.assertNotIn("private-producer-output", result.stdout + result.stderr)
        return result.stdout

    def test_unrelated_edit_is_silent_and_does_not_sync(self):
        self.assertEqual(self.invoke(self.event("*** Update File: src/app.py\n@@\n-a\n+b")), "")

    def test_other_repository_agents_file_does_not_sync(self):
        self.assertEqual(self.invoke(self.event("*** Update File: AGENTS.md\n@@\n-a\n+b", self.other)), "")

    def test_source_uses_event_cwd_not_process_cwd(self):
        self.assertEqual(self.invoke(self.event("*** Update File: AGENTS.md\n@@\n-a\n+b"), 1), "")

    def test_absolute_source_and_multifile_patch_sync_once(self):
        body = "*** Update File: {}\n@@\n-a\n+b\n*** Update File: mcp-servers.json\n@@\n-a\n+b".format(self.root / "AGENTS.md")
        self.assertEqual(self.invoke(self.event(body), 1), "")

    def test_shared_skill_add_and_native_skill_delete(self):
        for body in ("*** Add File: .agents/skills/new/SKILL.md\n+# New",
                     "*** Delete File: .codex/skills/old/SKILL.md"):
            with self.subTest(body=body):
                self.calls.write_text("")
                self.assertEqual(self.invoke(self.event(body), 1), "")

    def test_move_into_and_out_of_inventory(self):
        for old, new in (("notes.md", ".agents/skills/new/SKILL.md"),
                         (".agents/skills/old/SKILL.md", "notes.md")):
            with self.subTest(old=old):
                self.calls.write_text("")
                body = "*** Update File: {}\n*** Move to: {}\n@@\n-a\n+b".format(old, new)
                self.assertEqual(self.invoke(self.event(body), 1), "")

    def test_shared_reference_and_generated_output_do_not_sync(self):
        for path in (".agents/skills/reviewer/references/details.md", ".codex/config.toml",
                     ".codex/AGENTS.md", ".agents/skills/new/references/SKILL.md"):
            with self.subTest(path=path):
                self.assertEqual(self.invoke(self.event("*** Update File: " + path + "\n@@\n-a\n+b")), "")

    def test_native_protocol_and_generator_are_sources(self):
        for path in (".codex/skills/pir2/references/protocol.md", "etc/sync-codex.sh"):
            with self.subTest(path=path):
                self.calls.write_text("")
                self.assertEqual(self.invoke(self.event("*** Update File: " + path + "\n@@\n-a\n+b"), 1), "")

    def test_embedded_header_and_shell_text_are_not_executed(self):
        body = "*** Add File: example.txt\n+*** Update File: AGENTS.md\n+$(touch SHOULD_NOT_EXIST)"
        self.assertEqual(self.invoke(self.event(body)), "")
        self.assertFalse((self.other / "SHOULD_NOT_EXIST").exists())

    def test_path_traversal_outside_repo_is_ignored(self):
        self.assertEqual(self.invoke(self.event("*** Update File: ../application/AGENTS.md\n@@\n-a\n+b")), "")

    def test_symlink_to_source_resolves(self):
        alias = self.other / "source-alias"
        alias.symlink_to(self.root, target_is_directory=True)
        self.addCleanup(alias.unlink)
        self.assertEqual(self.invoke(self.event("*** Update File: source-alias/AGENTS.md\n@@\n-a\n+b", self.other), 1), "")

    def test_symlink_escaping_repo_is_ignored(self):
        alias = self.root / "outside"
        alias.symlink_to(self.other, target_is_directory=True)
        self.addCleanup(alias.unlink)
        self.assertEqual(self.invoke(self.event("*** Update File: outside/AGENTS.md\n@@\n-a\n+b")), "")

    def test_unknown_tool_is_ignored(self):
        event = self.event("*** Update File: AGENTS.md")
        event["tool_name"] = "Bash"
        self.assertEqual(self.invoke(event), "")

    def test_malformed_event_reports_without_sync(self):
        for event in ("not json", "[]", json.dumps({"hook_event_name": "PostToolUse", "tool_name": "apply_patch"})):
            with self.subTest(event=event):
                output = self.invoke(event, raw=True)
                self.assertEqual(json.loads(output)["hookSpecificOutput"]["hookEventName"], "PostToolUse")

    def test_failure_report_is_nonblocking_and_contains_no_producer_log(self):
        output = self.invoke(self.event("*** Update File: AGENTS.md\n@@\n-a\n+b"), 1, failure=True)
        context = json.loads(output)["hookSpecificOutput"]["additionalContext"]
        self.assertIn("exit 23", context)

    def test_existing_hook_trust_is_preserved_not_minted(self):
        self.assertEqual(self.config["hooks"]["state"],
                         {"fixture": {"trusted_hash": "existing-state-do-not-change"}})


if __name__ == "__main__":
    unittest.main(verbosity=2)
