#!/usr/bin/env bash
# Antigravity (Gemini) sync / config 契約テスト。
#
#   bash etc/test-antigravity-contracts.sh
#
# ライブドットファイルの生成物を --check で検証し、ルールサマリー、MCPフィルタ、
# hooks/auto-gateの構文、skills symlinkを確認する。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/antigravity-contracts.XXXXXX")"
trap 'find "$WORK" -mindepth 1 -delete 2>/dev/null; rmdir "$WORK" 2>/dev/null || true' EXIT

fail=0
pass=0

ok() { echo "PASS: $*"; pass=$((pass + 1)); }
bad() { echo "FAIL: $*" >&2; fail=$((fail + 1)); }

# --- A. sync --check / idempotent ---
if bash "${SCRIPT_DIR}/sync-antigravity.sh" --check >/dev/null; then
  ok "sync-antigravity --check"
else
  bad "sync-antigravity --check"
fi

RULE="${DOT_DIR}/.gemini/config/rules/shared-agents.md"
MCP="${DOT_DIR}/.gemini/config/mcp_config.json"
HOOKS="${DOT_DIR}/.gemini/config/hooks.json"
SCRIPT="${DOT_DIR}/.gemini/config/scripts/auto-gate.py"
SKILLS="${DOT_DIR}/.gemini/config/skills"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"

# --- B. rules = summary, not full copy ---
if [ -f "$RULE" ] \
  && grep -q 'AUTO-GENERATED by dotfiles/etc/sync-antigravity.sh' "$RULE" \
  && grep -q 'Do \*\*not\*\* treat this rule as a full copy' "$RULE" \
  && [ "$(wc -c <"$RULE")" -lt "$(wc -c <"$AGENTS_SRC")" ]; then
  ok "rules summary-not-full-copy"
else
  bad "rules summary-not-full-copy"
fi

# --- C. MCP filter ---
if command -v jq >/dev/null 2>&1; then
  if jq -e '._generated_by == "dotfiles/etc/sync-antigravity.sh"' "$MCP" >/dev/null; then
    ok "mcp _generated_by marker"
  else
    bad "mcp _generated_by marker"
  fi

  leaked="$(
    jq -r --argjson out "$(jq '.mcpServers // {}' "$MCP")" '
      .mcpServers
      | to_entries[]
      | select(.value.claudeCodeOnly == true or .value.openCodeOnly == true or .value.codexOnly == true or .value.cursorOnly == true)
      | .key as $k
      | select($out[$k] != null)
      | $k
    ' "${DOT_DIR}/mcp-servers.json"
  )"
  if [ -z "$leaked" ]; then
    ok "mcp other-runtime-only excluded"
  else
    bad "mcp leaked servers: $leaked"
  fi
else
  bad "jq required for MCP assertions"
fi

# --- D. hooks and auto-gate script ---
if [ -f "$HOOKS" ]; then
  ok "hooks.json exists"
else
  bad "hooks.json missing"
fi

if [ -f "$SCRIPT" ] && [ -x "$SCRIPT" ]; then
  ok "auto-gate.py executable"
else
  bad "auto-gate.py missing or not executable"
fi

if command -v python3 >/dev/null 2>&1; then
  if python3 -c 'import sys; compile(sys.stdin.read(), sys.argv[1], "exec")' "$SCRIPT" < "$SCRIPT" 2>/dev/null; then
    ok "auto-gate.py syntax valid"
  else
    bad "auto-gate.py syntax error"
  fi
else
  bad "python3 required for auto-gate.py syntax assertion"
fi

# --- E. skills symlink ---
if [ -d "$SKILLS" ] && [ "$(cd -P "$SKILLS" && pwd)" = "$(cd -P "${DOT_DIR}/.agents/skills" && pwd)" ]; then
  ok "skills linked/available"
else
  bad "skills missing"
fi

# --- F. sync publication guards on a private repository fixture ---
sync_fixture="${WORK}/sync-fixture"
mkdir -p "$sync_fixture/etc" "$sync_fixture/.gemini/config/rules"
cp "${SCRIPT_DIR}/sync-antigravity.sh" "$sync_fixture/etc/sync-antigravity.sh"
printf '%s\n' '{"mcpServers":{}}' >"$sync_fixture/mcp-servers.json"
printf '%s\n' '# private Antigravity fixture' >"$sync_fixture/AGENTS.md"
chmod +x "$sync_fixture/etc/sync-antigravity.sh"
if (cd "$sync_fixture" && bash etc/sync-antigravity.sh >/dev/null 2>&1); then
  ok "sync-antigravity private fixture generation"
else
  bad "sync-antigravity private fixture generation"
fi

sync_rule="${sync_fixture}/.gemini/config/rules/shared-agents.md"
producer_fail_bin="${WORK}/antigravity-producer-fail-bin"
producer_fail_log="${WORK}/antigravity-producer-fail.log"
mkdir -p "$producer_fail_bin"
printf '%s\n' '#!/bin/sh' 'printf "%s\\n" "PARTIAL_RULE_PRODUCER"' 'exit 23' >"$producer_fail_bin/cat"
chmod +x "$producer_fail_bin/cat"
producer_before="$(shasum "$sync_rule" | awk '{print $1}')"
if (cd "$sync_fixture" && PATH="$producer_fail_bin:$PATH" bash etc/sync-antigravity.sh) >"$producer_fail_log" 2>&1; then
  bad "sync-antigravity failed rule producer returns failure"
else
  ok "sync-antigravity failed rule producer returns failure"
fi
producer_after="$(shasum "$sync_rule" | awk '{print $1}')"
[ "$producer_before" = "$producer_after" ] && ok "sync-antigravity failed rule producer leaves target unchanged" || bad "sync-antigravity failed rule producer leaves target unchanged"
if grep -q 'PARTIAL_RULE_PRODUCER' "$sync_rule"; then
  bad "sync-antigravity failed rule producer published partial output"
else
  ok "sync-antigravity failed rule producer does not publish partial output"
fi

sync_rule_target="${WORK}/antigravity-generated-rule.md"
cp "$sync_rule" "$sync_rule_target"
rm -f "$sync_rule"
ln -s "$sync_rule_target" "$sync_rule"
if (cd "$sync_fixture" && bash etc/sync-antigravity.sh >/dev/null 2>&1); then
  bad "sync-antigravity rejects generated file symlink"
else
  ok "sync-antigravity rejects generated file symlink"
fi
[ -L "$sync_rule" ] && ok "sync-antigravity preserves generated file symlink" || bad "sync-antigravity preserves generated file symlink"

sync_rule_dir="${WORK}/antigravity-generated-rule-dir"
mkdir "$sync_rule_dir"
rm -f "$sync_rule"
ln -s "$sync_rule_dir" "$sync_rule"
if (cd "$sync_fixture" && bash etc/sync-antigravity.sh >/dev/null 2>&1); then
  bad "sync-antigravity rejects generated directory symlink"
else
  ok "sync-antigravity rejects generated directory symlink"
fi
[ -L "$sync_rule" ] && ok "sync-antigravity preserves directory symlink" || bad "sync-antigravity preserves directory symlink"
if [ -z "$(find "$sync_rule_dir" -mindepth 1 -print -quit 2>/dev/null)" ]; then
  ok "sync-antigravity leaves directory symlink target empty"
else
  bad "sync-antigravity leaves directory symlink target empty"
fi

rm -f "$sync_rule"
mkdir "$sync_rule"
if (cd "$sync_fixture" && bash etc/sync-antigravity.sh >/dev/null 2>&1); then
  bad "sync-antigravity rejects generated directory target"
else
  ok "sync-antigravity rejects generated directory target"
fi
if [ -z "$(find "$sync_rule" -mindepth 1 -print -quit 2>/dev/null)" ]; then
  ok "sync-antigravity leaves directory target empty"
else
  bad "sync-antigravity leaves directory target empty"
fi
rmdir "$sync_rule"
cp "$sync_rule_target" "$sync_rule"
sync_mcp="${sync_fixture}/.gemini/config/mcp_config.json"
sync_mcp_target="${WORK}/antigravity-generated-mcp.json"
cp "$sync_mcp" "$sync_mcp_target"
sync_mcp_before="$(shasum "$sync_mcp_target" | awk '{print $1}')"
rm -f "$sync_mcp"
ln -s "$sync_mcp_target" "$sync_mcp"
if (cd "$sync_fixture" && bash etc/sync-antigravity.sh >/dev/null 2>&1); then
  bad "sync-antigravity rejects generated MCP file symlink"
else
  ok "sync-antigravity rejects generated MCP file symlink"
fi
[ -L "$sync_mcp" ] && ok "sync-antigravity preserves generated MCP file symlink" || bad "sync-antigravity preserves generated MCP file symlink"
sync_mcp_after="$(shasum "$sync_mcp_target" | awk '{print $1}')"
[ "$sync_mcp_before" = "$sync_mcp_after" ] && ok "sync-antigravity leaves MCP symlink target unchanged" || bad "sync-antigravity leaves MCP symlink target unchanged"

echo "Antigravity contracts: pass=${pass} fail=${fail}"
[ "$fail" -eq 0 ]
