#!/usr/bin/env bash
# Cursor sync / seed / link 契約テスト（第3波）。
#
#   bash etc/test-cursor-contracts.sh
#
# ライブドットファイルの生成物を --check で検証し、seed 非破壊・link ヘルパー・
# skills-cursor 非接触を mktemp フィクスチャで確認する。本番 HOME への破壊的書き込みはしない。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/cursor-contracts.XXXXXX")"
trap 'find "$WORK" -mindepth 1 -delete 2>/dev/null; rmdir "$WORK" 2>/dev/null || true' EXIT

fail=0
pass=0

ok() { echo "PASS: $*"; pass=$((pass + 1)); }
bad() { echo "FAIL: $*" >&2; fail=$((fail + 1)); }

assert_true() {
  local name="$1"
  shift
  if "$@"; then
    ok "$name"
  else
    bad "$name"
  fi
}

assert_eq() {
  local name="$1" got="$2" want="$3"
  if [ "$got" = "$want" ]; then
    ok "$name"
  else
    bad "$name (got=$(printf '%q' "$got") want=$(printf '%q' "$want"))"
  fi
}

# --- A. sync --check / idempotent ---
if bash "${SCRIPT_DIR}/sync-cursor.sh" --check >/dev/null; then
  ok "sync-cursor --check"
else
  bad "sync-cursor --check"
fi

RULE="${DOT_DIR}/.cursor/rules/shared-agents.mdc"
MCP="${DOT_DIR}/.cursor/mcp.json"
AGENTS_SRC="${DOT_DIR}/AGENTS.md"

# --- B. rules = summary, not full copy ---
if [ -f "$RULE" ] \
  && grep -q 'AUTO-GENERATED by dotfiles/etc/sync-cursor.sh' "$RULE" \
  && grep -q 'Do \*\*not\*\* treat this rule as a full copy' "$RULE" \
  && [ "$(wc -c <"$RULE")" -lt "$(wc -c <"$AGENTS_SRC")" ]; then
  ok "rules summary-not-full-copy"
else
  bad "rules summary-not-full-copy"
fi

# --- C. MCP filter ---
if command -v jq >/dev/null 2>&1; then
  if jq -e '._generated_by == "dotfiles/etc/sync-cursor.sh"' "$MCP" >/dev/null; then
    ok "mcp _generated_by marker"
  else
    bad "mcp _generated_by marker"
  fi

  leaked="$(
    jq -r --argjson out "$(jq '.mcpServers // {}' "$MCP")" '
      .mcpServers
      | to_entries[]
      | select(.value.claudeCodeOnly == true or .value.openCodeOnly == true or .value.codexOnly == true)
      | .key as $k
      | select($out[$k] != null)
      | $k
    ' "${DOT_DIR}/mcp-servers.json"
  )"
  if [ -z "$leaked" ]; then
    ok "mcp excludes claudeCodeOnly/openCodeOnly/codexOnly"
  else
    bad "mcp leaked exclusive servers: $leaked"
  fi

  remote_leak="$(
    jq -r '
      (.mcpServers // {}) | to_entries[]
      | select(.value.type == "remote")
      | .key
    ' "$MCP"
  )"
  if [ -z "$remote_leak" ]; then
    ok "mcp has no type=remote residues"
  else
    bad "mcp still has type=remote: $remote_leak"
  fi
else
  bad "jq required for MCP assertions"
fi

# --- D. seed non-destructive on existing overlays ---
if [ -f "${DOT_DIR}/.cursor/agents/explorer.md" ]; then
  before="$(cksum "${DOT_DIR}/.cursor/agents/explorer.md" | awk '{print $1" "$2}')"
  bash "${SCRIPT_DIR}/seed-cursor-overlay.sh" >/dev/null
  after="$(cksum "${DOT_DIR}/.cursor/agents/explorer.md" | awk '{print $1" "$2}')"
  assert_eq "seed does not overwrite explorer.md" "$after" "$before"
else
  bad "explorer.md missing (cannot test seed non-destructive)"
fi

# --- E. phase-3 inventory present ---
missing=""
for a in codex-runner explorer implementer reviewer planner; do
  [ -f "${DOT_DIR}/.cursor/agents/${a}.md" ] || missing="${missing} agent:${a}"
done
for s in pir2 pir2codex codex epic deepthink research ai-design-system ai-diary ai-ltm unity-mcp-skill dotfiles-autosync field-notes; do
  [ -f "${DOT_DIR}/.cursor/skills/${s}/SKILL.md" ] || missing="${missing} skill:${s}"
done
for s in deepthink research epic; do
  [ -f "${DOT_DIR}/.agents/skills/${s}/SKILL.md" ] || missing="${missing} shared:${s}"
done
if [ -z "$missing" ]; then
  ok "phase-3 inventory (agents/skills/shared)"
else
  bad "phase-3 inventory missing:${missing}"
fi

# --- E2. Cursor slash names: name == folder (bare basename, no cursor- prefix) ---
bad_names=""
legacy=""
for skill_md in "${DOT_DIR}/.cursor/skills"/*/SKILL.md; do
  [ -f "$skill_md" ] || continue
  d="$(basename "$(dirname "$skill_md")")"
  case "$d" in
    cursor-*) legacy="${legacy} ${d}" ;;
  esac
  got="$(awk '
    NR == 1 && $0 == "---" { fm = 1; next }
    fm && $0 == "---" { exit }
    fm && /^name:/ {
      sub(/^name:[[:space:]]*/, "")
      gsub(/["'\'']/, "")
      print
      exit
    }
  ' "$skill_md")"
  if [ "$got" != "$d" ]; then
    bad_names="${bad_names} ${d}:${got:-<empty>}!=${d}"
  fi
done
if [ -z "$bad_names" ] && [ -z "$legacy" ]; then
  ok "cursor skill dirs/names (bare basename and name==folder)"
else
  [ -n "$bad_names" ] && bad "cursor skill name mismatch:${bad_names}"
  [ -n "$legacy" ] && bad "cursor skill legacy cursor-* dirs:${legacy}"
fi

# --- F. link helpers: refuse non-symlink mcp + skills materialize + skills-cursor untouched ---
fake_home="${WORK}/home"
mkdir -p "${fake_home}/.cursor/skills-cursor" "${fake_home}/.cursor/skills"
printf 'MARKER\n' >"${fake_home}/.cursor/skills-cursor/MARKER"
printf 'HAND_EDITED\n' >"${fake_home}/.cursor/mcp.json"

link_cursor_file() {
  local src="$1" dest="$2"
  if [ -e "$dest" ] || [ -L "$dest" ]; then
    if [ ! -L "$dest" ]; then
      echo "refuse non-symlink $dest"
      return 0
    fi
  fi
  ln -sfn "$src" "$dest"
}

materialize_cursor_skill() {
  local src="$1" dest="$2" name
  name="$(basename "$src")"
  if [ "$name" = "skills-cursor" ]; then
    echo "refuse skills-cursor"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  if [ -L "$dest" ] || [ -e "$dest" ]; then
    rm -rf "$dest"
  fi
  mkdir -p "$dest"
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$src"/ "$dest"/
  else
    cp -a "$src"/. "$dest"/
  fi
  echo "materialized $dest"
}

# Attempt to "link" over hand-edited mcp.json — must refuse
out="$(link_cursor_file "${DOT_DIR}/.cursor/mcp.json" "${fake_home}/.cursor/mcp.json" 2>&1 || true)"
content="$(cat "${fake_home}/.cursor/mcp.json")"
assert_eq "link refuses non-symlink mcp.json content" "$content" "HAND_EDITED"
assert_true "link refuse message" grep -q 'refuse non-symlink' <<<"$out"
assert_eq "skills-cursor MARKER intact" "$(cat "${fake_home}/.cursor/skills-cursor/MARKER")" "MARKER"

# Materialize replaces symlink with a real directory and copies SKILL.md
sample_skill="${DOT_DIR}/.cursor/skills/check-updates"
if [ -d "$sample_skill" ]; then
  ln -sfn /nonexistent/path "${fake_home}/.cursor/skills/check-updates"
  materialize_cursor_skill "$sample_skill" "${fake_home}/.cursor/skills/check-updates" >/dev/null
  if [ -d "${fake_home}/.cursor/skills/check-updates" ] \
    && [ ! -L "${fake_home}/.cursor/skills/check-updates" ] \
    && [ -f "${fake_home}/.cursor/skills/check-updates/SKILL.md" ]; then
    ok "materialize_cursor_skill creates real dir (not symlink)"
  else
    bad "materialize_cursor_skill creates real dir (not symlink)"
  fi
  assert_eq "skills-cursor MARKER intact after materialize" "$(cat "${fake_home}/.cursor/skills-cursor/MARKER")" "MARKER"
else
  bad "check-updates skill missing for materialize test"
fi

# Static: link.sh materializes skills (not per-skill symlink) + excludes .cursor from glob
if grep -q 'materialize_cursor_skill' "${DOT_DIR}/etc/link.sh" \
  && ! grep -q 'link_cursor_dir "\$cursor_skill"' "${DOT_DIR}/etc/link.sh"; then
  ok "link.sh materializes cursor skills (not symlink)"
else
  bad "link.sh should materialize cursor skills"
fi

if grep -q '\[ "\$f" = "\.cursor" \] && continue' "${DOT_DIR}/etc/link.sh"; then
  ok "link.sh excludes .cursor from whole-dir symlink"
else
  bad "link.sh missing .cursor exclusion"
fi

# --- G. codex-runner stdin prompt contract across Claude/Cursor/OpenCode ---
CLAUDE_CODEX_RUNNER="${DOT_DIR}/.claude/agents/codex-runner.md"
CURSOR_CODEX_RUNNER="${DOT_DIR}/.cursor/agents/codex-runner.md"

no_legacy_prompt_arg() {
  ! grep -Eq "^[[:space:]]+''[[:space:]]+>" "$1"
}

assert_true "Claude codex-runner uses '-' prompt argument" \
  grep -Eq "^[[:space:]]+- >" "$CLAUDE_CODEX_RUNNER"
assert_true "Cursor codex-runner uses '-' prompt argument" \
  grep -Eq "^[[:space:]]+- >" "$CURSOR_CODEX_RUNNER"
assert_true "Claude codex-runner has no legacy empty prompt argument" \
  no_legacy_prompt_arg "$CLAUDE_CODEX_RUNNER"
assert_true "Cursor codex-runner has no legacy empty prompt argument" \
  no_legacy_prompt_arg "$CURSOR_CODEX_RUNNER"
assert_true "Claude codex-runner description is quoted scalar" \
  grep -Eq 'description: "[^"]*"$' "$CLAUDE_CODEX_RUNNER"
assert_true "Cursor codex-runner description is quoted scalar" \
  grep -Eq 'description: "[^"]*"$' "$CURSOR_CODEX_RUNNER"

if HOME="$fake_home" bash "${SCRIPT_DIR}/sync-opencode.sh" >/dev/null; then
  OPENCODE_CODEX_RUNNER="${fake_home}/.config/opencode/agents/codex-runner.md"
  assert_true "generated OpenCode codex-runner exists" \
    test -f "$OPENCODE_CODEX_RUNNER"
  assert_true "generated OpenCode codex-runner uses '-' prompt argument" \
    grep -Eq "^[[:space:]]+- >" "$OPENCODE_CODEX_RUNNER"
  assert_true "generated OpenCode codex-runner has no legacy empty prompt argument" \
    no_legacy_prompt_arg "$OPENCODE_CODEX_RUNNER"
else
  bad "sync-opencode with fake HOME"
fi

# --- H. Cursor overlay vocabulary / legacy dir gates ---
assert_true "dotfiles-autosync skill exists" \
  test -f "${DOT_DIR}/.cursor/skills/dotfiles-autosync/SKILL.md"
legacy_dirs=$(find "${DOT_DIR}/.cursor/skills" -maxdepth 1 -type d -name 'cursor-*' 2>/dev/null || true)
if [ -n "$legacy_dirs" ]; then
  bad "legacy cursor-* skill directories remain: ${legacy_dirs}"
else
  ok "no legacy cursor-* skill directories"
fi
agent_hits=$(grep -RIn 'Agent 起動' "${DOT_DIR}/.cursor/skills" --include='*.md' 2>/dev/null || true)
if [ -n "$agent_hits" ]; then
  bad "found Agent 起動 in cursor skills: ${agent_hits}"
else
  ok "no Agent 起動 wording in cursor skills"
fi
legacy_fc_hits=$(grep -RIn '<function_calls>' "${DOT_DIR}/.cursor/skills" --include='*.md' 2>/dev/null || true)
if [ -n "$legacy_fc_hits" ]; then
  bad "found legacy <function_calls> in cursor skills: ${legacy_fc_hits}"
else
  ok "no legacy <function_calls> in cursor skills"
fi

echo
echo "cursor contracts: ${pass} passed, ${fail} failed"
if [ "$fail" -ne 0 ]; then
  exit 1
fi
exit 0
