[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_i = 1
hook_source = '''
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

    autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_i = 1
hook_source = 'call coil398#init#vim_lsp#hook_source()'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_i = 1
