[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    call coil398#init#deoplete#hook_source()
    let g:deoplete#omni#input_patterns.go = '\w\.\w*'
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_i = 1
depends = 'deoplete.nvim'
hook_source = '''
    let g:LanguageClient_diagnosticsEnable = 0

    let g:LanguageClient_serverCommands = {
    \ 'python' : ['pyls'],
    \ 'c' : ['clangd'],
    \ 'cpp' : ['clangd'],
    \ 'sh' : ['bash-language-server', 'start'],
    \ 'ruby' : ['solargraph', 'stdio'],
    \ 'javascript' : ['javascript-typescript-stdio'],
    \ 'typescript' : ['javascript-typescript-stdio'],
    \ 'typescript.jsx' : ['javascript-typescript-stdio'],
    \ }
'''
hook_post_source = '''
    :LanguageClientStart
'''
