[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    call coil398#init#deoplete#hook_source()
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_i = 1
depends = 'deoplete.nvim'
hook_source = '''
    let g:LanguageClient_diagnosticsEnable = 0

    let g:LanguageClient_rootMakers = {
    \ 'haskell': ['*.cabal', 'stack.yaml'],
    \ }

    let g:LanguageClient_serverCommands = {
    \ 'python' : ['pyls'],
    \ 'c' : ['clangd'],
    \ 'cpp' : ['clangd'],
    \ 'sh' : ['bash-language-server', 'start'],
    \ 'ruby' : ['solargraph', 'stdio'],
    \ 'go' : ['gopls'],
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'haskell': ['hie-wrapper'],
    \ }
'''
hook_post_source = '''
    :LanguageClientStart
'''
