[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
    call coil398#init#deoplete#hook_source()
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_i = 1
depends = 'deoplete.nvim'
hook_source = '''
    call coil398#init#LCnvim#hook_source()
'''
hook_post_source = '''
    :LanguageClientStart
'''
